escape_string – JSON-Fortran
escape_string Subroutine
Jacob Williams
1/21/2014
Source File
Variables
i ipos c specials
Source Code
escape_string
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private subroutine escape_string(str_in, str_out)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str_in
character(kind=CK,len=:), intent(out), allocatable :: str_out
Description
Add the escape characters to a string for adding to JSON.
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
integer(kind=IK), public :: ipos
character(kind=CK,len=1), public :: c
character(kind=CK,len=*), public, parameter :: specials = quotation_mark//backslash//slash//bspace//formfeed//newline//carriage_return//horizontal_tab
Source Code
    subroutine escape_string(str_in, str_out)
    implicit none
    character(kind=CK,len=*),intent(in)              :: str_in
    character(kind=CK,len=:),allocatable,intent(out) :: str_out
    integer(IK) :: i,ipos
    character(kind=CK,len=1) :: c
    character(kind=CK,len=*),parameter :: specials = quotation_mark//&
                                                     backslash//&
                                                     slash//&
                                                     bspace//&
                                                     formfeed//&
                                                     newline//&
                                                     carriage_return//&
                                                     horizontal_tab
    !Do a quick scan for the special characters,
    ! if any are present, then process the string,
    ! otherwise, return the string as is.
    if (scan(str_in,specials)>0) then
        str_out = repeat(space,chunk_size)
        ipos = 1
        !go through the string and look for special characters:
        do i=1,len(str_in)
            c = str_in(i:i)    !get next character in the input string
            !if the string is not big enough, then add another chunk:
            if (ipos+3>len(str_out)) str_out = str_out // repeat(space, chunk_size)
            select case(c)
            case(quotation_mark,backslash,slash)
                str_out(ipos:ipos+1) = backslash//c
                ipos = ipos + 2
            case(bspace)
                str_out(ipos:ipos+1) = '\b'
                ipos = ipos + 2
            case(formfeed)
                str_out(ipos:ipos+1) = '\f'
                ipos = ipos + 2
            case(newline)
                str_out(ipos:ipos+1) = '\n'
                ipos = ipos + 2
            case(carriage_return)
                str_out(ipos:ipos+1) = '\r'
                ipos = ipos + 2
            case(horizontal_tab)
                str_out(ipos:ipos+1) = '\t'
                ipos = ipos + 2
            case default
                str_out(ipos:ipos) = c
                ipos = ipos + 1
            end select
        end do
        !trim the string if necessary:
        if (ipos<len(str_out)+1) then
            if (ipos==1) then
                str_out = ''
            else
                str_out = str_out(1:ipos-1)
            end if
        end if
    else
        str_out = str_in
    end if
    end subroutine escape_string
Call graph
json_value_add_string calls escape_string, json_add
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_name_ascii calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
json_add calls json_value_add_string, wrap_json_value_add_string, json_value_add_string_name_ascii, json_value_add_string_val_ascii, json_value_add_integer_vec, json_value_add_double, json_value_add_integer, json_value_add_logical_vec, json_value_add_string_vec, json_value_add_logical, json_value_add_double_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_double, wrap_json_value_add_integer, wrap_json_value_add_logical_vec, wrap_json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical, wrap_json_value_add_double_vec
json_update_logical calls json_add
json_update_integer calls json_add
example2 calls json_add
parse_array calls json_add, parse_value
add_variables_to_input calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_value_add_integer_vec calls json_add
json_value_add_double calls json_add
json_value_add_integer calls json_add
test_2 calls json_add, add_variables_to_input, json_update
json_value_add_logical_vec calls json_add
test_12 calls json_add, json_update
json_value_add_string_vec calls json_add
test_4 calls json_add
parse_object calls json_add, parse_object, parse_value
json_value_add_logical calls json_add
test_7 calls json_add
json_value_add_double_vec calls json_add
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_integer, json_update_double, json_update_string, wrap_json_update_logical, wrap_json_update_integer, wrap_json_update_double, wrap_json_update_string, json_update_string_name_ascii, json_update_string_val_ascii
rename calls json_update
json_file_update_logical calls json_update
json_file_update_string calls json_update
test_1 calls json_update
test_10 calls json_update
json_file_update_real calls json_update
json_file_update_integer calls json_update
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_update_integer calls json_update_integer
parse_value calls parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
test_8 calls json_parse
test_14 calls json_parse
json_file_load calls json_parse
json_file_load_from_string calls json_parse
jf_test_8 calls test_8
jf_test_14 calls test_14
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_update_double calls json_update_double
wrap_json_update_string calls json_update_string
json_update_string_name_ascii calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
wrap_json_value_add_double calls json_value_add_double
wrap_json_value_add_integer calls json_value_add_integer
jf_test_2 calls test_2
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
jf_test_12 calls test_12
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
jf_test_4 calls test_4
wrap_json_value_add_logical calls json_value_add_logical
jf_test_7 calls test_7
wrap_json_value_add_double_vec calls json_value_add_double_vec