json_parse_file – JSON-Fortran
json_parse_file Subroutine
Source File
Variables
iunit istat is_open
Source Code
json_parse_file
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private subroutine json_parse_file(file, p, unit)
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in) :: file
JSON file name
type(json_value), , pointer :: p
output structure
integer(kind=IK), intent(in), optional :: unit
file unit number (/= 0)
Description
Parse the JSON file and populate the json_value tree.
Inputs
The inputs can be:
file and unit : the specified unit is used to read JSON from file. [note if unit is already open, then the filename is ignored]
file : JSON is read from file using internal unit number
Example
    type(json_value),pointer :: p
    call json_parse(file='myfile.json', p=p)
History
Jacob Williams : 01/13/2015 : added read from string option.
Izaak Beekman : 03/08/2015 : moved read from string to separate subroutine, and error annotation to separate subroutine.
Note
When calling this routine, any exceptions thrown from previous calls will automatically be cleared.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: iunit
integer(kind=IK), public :: istat
logical(kind=LK), public :: is_open
Source Code
    subroutine json_parse_file(file, p, unit)
    implicit none
    character(kind=CDK,len=*),intent(in) :: file  !! JSON file name
    type(json_value),pointer             :: p     !! output structure
    integer(IK),intent(in),optional      :: unit  !! file unit number (/= 0)
    integer(IK) :: iunit, istat
    logical(LK) :: is_open
    !clear any exceptions and initialize:
    call json_initialize()
    if ( present(unit) ) then
        if (unit==0) then
            call throw_exception('Error in json_parse_file: unit number must not be 0.')
            return
        end if
        iunit = unit
        !check to see if the file is already open
        ! if it is, then use it, otherwise open the file with the name given.
        inquire(unit=iunit, opened=is_open, iostat=istat)
        if (istat==0 .and. .not. is_open) then
           ! open the file
            open (  unit        = iunit, &
                    file        = file, &
                    status      = 'OLD', &
                    action      = 'READ', &
                    form        = form_spec, &
                    access      = access_spec, &
                    iostat      = istat &
                    FILE_ENCODING )
        else
            !if the file is already open, then we need to make sure
            ! that it is open with the correct form/access/etc...
        end if
    else
        ! open the file with a new unit number:
        open (  newunit     = iunit, &
                file        = file, &
                status      = 'OLD', &
                action      = 'READ', &
                form        = form_spec, &
                access      = access_spec, &
                iostat      = istat &
                FILE_ENCODING )
    end if
    if (istat==0) then
        ! create the value and associate the pointer
        call json_value_create(p)
        ! Note: the name of the root json_value doesn't really matter,
        !  but we'll allocate something here just in case.
        p%name = trim(file)  !use the file name
        ! parse as a value
        call parse_value(unit=iunit, str=CK_'', value=p)
        if (exception_thrown) call annotate_invalid_json(iunit,CK_'')
        ! close the file if necessary
        close(unit=iunit, iostat=istat)
    else
        call throw_exception('Error in json_parse_file: Error opening file: '//trim(file))
        nullify(p)
    end if
    end subroutine json_parse_file
Call graph
json_parse_file calls annotate_invalid_json, json_initialize, parse_value, throw_exception, json_value_create
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
json_initialize calls throw_exception, json_clear_exceptions
parse_value calls throw_exception, parse_array, parse_string, to_logical, pop_char, push_char, to_null, to_array, to_object, parse_for_chars, to_string, parse_object, parse_number
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_array calls parse_value, throw_exception, json_value_create, pop_char, json_destroy, json_add
parse_string calls throw_exception, pop_char, valid_json_hex
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
to_array calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
to_string calls destroy_json_data
parse_object calls parse_value, throw_exception, json_value_create, parse_string, pop_char, parse_object, json_destroy, json_add
parse_number calls throw_exception, pop_char, push_char, to_integer, to_double, string_to_integer, string_to_double
json_destroy calls json_value_destroy
json_add calls wrap_json_value_add_integer, wrap_json_value_add_string, json_value_add_logical_vec, json_value_add_integer_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_logical, json_value_add_integer, json_value_add_double_vec, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, json_value_add_string_val_ascii, json_value_add_double, wrap_json_value_add_double, json_value_add_logical, json_value_add_string, json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_name_ascii, json_value_add_string_vec_val_ascii, json_value_add_member
json_value_destroy calls json_value_destroy, destroy_json_data
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
wrap_json_value_add_string calls json_value_add_string, to_unicode
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_integer_vec calls json_value_create, to_array, json_add
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, to_array, json_add
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
to_unicode calls to_uni, to_uni_vec
to_integer calls destroy_json_data
to_double calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_parse calls json_parse_file
test_8 calls json_parse
test_14 calls json_parse
json_file_load calls json_parse
json_file_load_from_string calls json_parse
jf_test_8 calls test_8
jf_test_14 calls test_14
wrap_json_file_load_from_string calls json_file_load_from_string