json_get_by_path – JSON-Fortran
json_get_by_path Subroutine
Source File
Variables
start_array_alt end_array_alt root this child i length child_i c array tmp
Source Code
json_get_by_path
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private subroutine json_get_by_path(me, path, p, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
type(json_value), intent(out), pointer :: p
logical(kind=LK), intent(out), optional :: found
true if it was found
Description
Returns the json_value pointer given the path string.
Example
     type(json_value),pointer :: dat,p
     logical :: found
     !...
     call json_get(dat,'data(2).version',p,found)
Notes
The following special characters are used to denote paths:
  $         - root
  @         - this
  .         - child object member
  [] or ()  - child array element
Thus, if any of these characters are present in the name key, this routine cannot be used to get the value. In that case, the json_get_child routines would need to be used.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=1), public, parameter :: start_array_alt = '('
character(kind=CK,len=1), public, parameter :: end_array_alt = ')'
character(kind=CK,len=1), public, parameter :: root = '$'
character(kind=CK,len=1), public, parameter :: this = '@'
character(kind=CK,len=1), public, parameter :: child = '.'
integer(kind=IK), public :: i
integer(kind=IK), public :: length
integer(kind=IK), public :: child_i
character(kind=CK,len=1), public :: c
logical(kind=LK), public :: array
type(json_value), public, pointer :: tmp
Source Code
    subroutine json_get_by_path(me, path, p, found)
    implicit none
    type(json_value),pointer,intent(in)  :: me
    character(kind=CK,len=*),intent(in)  :: path
    type(json_value),pointer,intent(out) :: p
    logical(LK),intent(out),optional     :: found  !! true if it was found
    character(kind=CK,len=1),parameter :: start_array_alt = '('
    character(kind=CK,len=1),parameter :: end_array_alt   = ')'
    character(kind=CK,len=1),parameter :: root            = '$'
    character(kind=CK,len=1),parameter :: this            = '@'
    character(kind=CK,len=1),parameter :: child           = '.'
    integer(IK)              :: i,length,child_i
    character(kind=CK,len=1) :: c
    logical(LK)              :: array
    type(json_value),pointer :: tmp
    if (.not. exception_thrown) then
        nullify(p)
        ! default to assuming relative to this
        p => me
        child_i = 1
        array = .false.
        length = len_trim(path)
        do i=1, length
            c = path(i:i)
            select case (c)
            case (root)
                ! root
                do while (associated (p%parent))
                    p => p%parent
                end do
                child_i = i + 1
            case (this)
                ! this
                p => me
                child_i = i + 1
            case (child)
                ! get child member from p
                if (child_i < i) then
                    nullify(tmp)
                    call json_get_child(p, path(child_i:i-1), tmp)
                    p => tmp
                    nullify(tmp)
                else
                    child_i = i + 1
                    cycle
                end if
                if (.not. associated(p)) then
                    call throw_exception('Error in json_get_by_path:'//&
                                         ' Error getting child member.')
                    exit
                end if
                child_i = i+1
            case (start_array,start_array_alt)
                !....Modified to allow for 'var[3]' style syntax
                !Note: jmozmoz/fson has a slightly different version of this...
                ! start looking for the array element index
                array = .true.
                ! get child member from p
                if (child_i < i) then
                    nullify(tmp)
                    call json_get_child(p, path(child_i:i-1), tmp)
                    p => tmp
                    nullify(tmp)
                else
                    child_i = i + 1
                    cycle
                end if
                if (.not. associated(p)) then
                    call throw_exception('Error in json_get_by_path:'//&
                                         ' Error getting array element')
                    exit
                end if
                child_i = i + 1
            case (end_array,end_array_alt)
                if (.not.array) then
                    call throw_exception('Error in json_get_by_path: Unexpected ]')
                    exit
                end if
                array = .false.
                child_i = string_to_integer(path(child_i:i-1))
                nullify(tmp)
                call json_get_child(p, child_i, tmp)
                p => tmp
                nullify(tmp)
                child_i= i + 1
            end select
        end do
        if (exception_thrown) then
            if (present(found)) then
                found = .false.
                call json_clear_exceptions()
            end if
        else
            ! grab the last child if present in the path
            if (child_i <= length) then
                nullify(tmp)
                call json_get_child(p, path(child_i:i-1), tmp)
                p => tmp
                nullify(tmp)
            end if
            if (associated(p)) then
                if (present(found)) found = .true.    !everything seems to be ok
            else
                call throw_exception('Error in json_get_by_path:'//&
                                     ' variable not found: '//trim(path))
                if (present(found)) then
                    found = .false.
                    call json_clear_exceptions()
                end if
            end if
        end if
    else
        if (present(found)) found = .false.
    end if
    end subroutine json_get_by_path
Call graph
json_get_by_path calls json_get_child, json_clear_exceptions, throw_exception, string_to_integer
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
throw_exception calls json_throw_exception, wrap_json_throw_exception
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars, to_unicode
to_unicode calls to_uni, to_uni_vec
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
wrap_json_get_by_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
json_get calls json_get_by_path, json_get_integer_with_path, json_get_logical_with_path, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_double_with_path, wrap_json_get_integer_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_string_vec, json_get_logical_vec_with_path, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_string_with_path, wrap_json_get_double_with_path
test_2 calls json_get, json_update
json_file_get_integer_vec calls json_get
json_get_integer_vec_with_path calls json_get
json_file_get_integer calls json_get
json_update_logical calls json_get
json_file_get_string_vec calls json_get
json_update_double calls json_get
json_file_get_double_vec calls json_get
json_get_double_vec calls json_get
json_file_get_logical calls json_get
json_get_double_vec_with_path calls json_get
json_update_integer calls json_get
test_7 calls json_get
json_file_get_logical_vec calls json_get
json_file_get_double calls json_get
json_update_string calls json_get
test_12 calls json_get, json_update
json_get_logical_vec calls json_get
json_get_string_vec calls json_get
json_get_logical_vec_with_path calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_string calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_get_integer_vec calls json_get
rename calls json_get, json_update
jf_test_2 calls test_2
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_integer, json_update_string, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii
json_file_update_string calls json_update
test_1 calls json_update
json_file_update_integer calls json_update
json_file_update_real calls json_update
json_file_update_logical calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_update_double calls json_update_double
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_update_integer calls json_update_integer
jf_test_7 calls test_7
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_double calls json_file_get_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
jf_test_12 calls test_12
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_10 calls test_10
wrap_json_file_get_string calls json_file_get_string
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path
wrap_json_get_array_with_path calls json_get_array_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_double_with_path calls json_get_double_with_path