json_check_for_errors – JSON-Fortran
json_check_for_errors Subroutine
Jacob Williams
12/4/2013
Source File
public subroutine json_check_for_errors(status_ok, error_msg)
Arguments
Type Intent Optional Attributes Name
logical(kind=LK), intent(out) :: status_ok
true if there were no errors
character(kind=CK,len=:), intent(out), allocatable :: error_msg
the error message (if there were errors)
Description
Retrieve error code from the module. This should be called after json_parse to check for errors. If an error is thrown, before using the module again, json_initialize should be called to clean up before it is used again.
Example
     type(json_file) :: json
     logical :: status_ok
     character(kind=CK,len=:),allocatable :: error_msg
     call json%load_file(filename='myfile.json')
     call json_check_for_errors(status_ok, error_msg)
     if (.not. status_ok) then
         write(*,*) 'Error: '//error_msg
         call json_clear_exceptions()
         call json%destroy()
     end if
See also
json_failed
Called By
Source Code
    subroutine json_check_for_errors(status_ok, error_msg)
    implicit none
    logical(LK),intent(out) :: status_ok !! true if there were no errors
    character(kind=CK,len=:),allocatable,intent(out) :: error_msg !! the error message (if there were errors)
    status_ok = .not. exception_thrown
    if (.not. status_ok) then
        if (allocated(err_message)) then
            error_msg = err_message
        else
            error_msg = 'Error: json_initialize() must be called first to initialize the module.'
        end if
    else
        error_msg = ''
    end if
    end subroutine json_check_for_errors
Call graph
json_print_error_message calls json_check_for_errors
test_1 calls json_print_error_message
test_9 calls json_print_error_message
test_10 calls json_print_error_message
test_14 calls json_print_error_message
test_8 calls json_print_error_message
test_11 calls json_print_error_message
add_variables_to_input calls json_print_error_message
test_7 calls json_print_error_message
test_2 calls json_print_error_message, add_variables_to_input
test_5 calls json_print_error_message
test_3 calls json_print_error_message
test_6 calls json_print_error_message
test_13 calls json_print_error_message
test_4 calls json_print_error_message
jf_test_1 calls test_1
jf_test_9 calls test_9
jf_test_10 calls test_10
test_12 calls check_errors
jf_test_12 calls test_12
jf_test_14 calls test_14
jf_test_8 calls test_8
jf_test_11 calls test_11
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_5 calls test_5
jf_test_3 calls test_3
jf_test_6 calls test_6
jf_test_13 calls test_13
jf_test_4 calls test_4