json_get_string – JSON-Fortran
json_get_string Subroutine
Source File
Variables
s pre post j jprev n c
Source Code
json_get_string
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_parent json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_get_parent json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private subroutine json_get_string(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=:), intent(out), allocatable :: value
Description
Get a character string from a json_value.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=:), public, allocatable :: s
character(kind=CK,len=:), public, allocatable :: pre
character(kind=CK,len=:), public, allocatable :: post
integer(kind=IK), public :: j
integer(kind=IK), public :: jprev
integer(kind=IK), public :: n
character(kind=CK,len=1), public :: c
Source Code
    subroutine json_get_string(me, value)
    implicit none
    type(json_value),pointer,intent(in)              :: me
    character(kind=CK,len=:),allocatable,intent(out) :: value
    character(kind=CK ,len=:),allocatable :: s,pre,post
    integer(IK) :: j,jprev,n
    character(kind=CK,len=1) :: c
    value = ''
    if ( exception_thrown) return
    select case (me%var_type)
    case (json_string)
        if (allocated(me%str_value)) then
            !get the value as is:
            s = me%str_value
            ! Now, have to remove the escape characters:
            !
            ! '\"'        quotation mark
            ! '\\'        reverse solidus
            ! '\/'        solidus
            ! '\b'        backspace
            ! '\f'        formfeed
            ! '\n'        newline (LF)
            ! '\r'        carriage return (CR)
            ! '\t'        horizontal tab
            ! '\uXXXX'    4 hexadecimal digits
            !
            !initialize:
            n = len(s)
            j = 1
            do
                jprev = j                      !initialize
                j = index(s(j:n),backslash)    !look for an escape character
                if (j>0) then            !an escape character was found
                    !index in full string of the escape character:
                    j = j + (jprev-1)
                    if (j<n) then
                        !save the bit before the escape character:
                        if (j>1) then
                            pre = s( 1 : j-1 )
                        else
                            pre = ''
                        end if
                        !character after the escape character:
                        c = s( j+1 : j+1 )
                        if (any(c == [quotation_mark,backslash,slash, &
                             to_unicode(['b','f','n','r','t'])])) then
                            !save the bit after the escape characters:
                            if (j+2<n) then
                                 post = s(j+2:n)
                            else
                                 post = ''
                            end if
                            select case(c)
                            case (quotation_mark,backslash,slash)
                                !use c as is
                            case (CK_'b')
                                 c = bspace
                            case (CK_'f')
                                 c = formfeed
                            case (CK_'n')
                                 c = newline
                            case (CK_'r')
                                 c = carriage_return
                            case (CK_'t')
                                 c = horizontal_tab
                            end select
                            s = pre//c//post
                            n = n-1    !backslash character has been
                                       ! removed from the string
                        else if (c == 'u') then !expecting 4 hexadecimal digits after
                                                !the escape character    [\uXXXX]
                            !for now, we are just printing them as is
                            ![not checking to see if it is a valid hex value]
                            if (j+5<=n) then
                                j=j+4
                            else
                                call throw_exception('Error in json_get_string:'//&
                                                     ' Invalid hexadecimal sequence'//&
                                                     ' in string: '//trim(c))
                                exit
                            end if
                        else
                            !unknown escape character
                            call throw_exception('Error in json_get_string:'//&
                                                 ' unknown escape sequence in string "'//&
                                                 trim(s)//'" ['//backslash//c//']')
                            exit
                        end if
                        j=j+1    !go to the next character
                        if (j>=n) exit    !finished
                    else
                        !an escape character is the last character in
                        ! the string [this may not be valid syntax,
                        ! but just keep it]
                        exit
                    end if
                else
                    exit    !no more escape characters in the string
                end if
            end do
            if (exception_thrown) then
               if (allocated(value)) deallocate(value)
            else
               value = s
            end if
        else
           call throw_exception('Error in json_get_string:'//&
                ' me%value not allocated')
        end if
    case default
        call throw_exception('Error in json_get_string:'//&
             ' Unable to resolve value to characters: '//me%name)
        ! Note: for the other cases, we could do val to string conversions.
    end select
    !cleanup:
    if (allocated(s)) deallocate(s)
    if (allocated(pre)) deallocate(pre)
    if (allocated(post)) deallocate(post)
    end subroutine json_get_string
Call graph
json_get_string calls to_unicode, throw_exception
to_unicode calls to_uni_vec, to_uni
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_string_with_path calls json_get_string
wrap_json_get_string_with_path calls json_get_string_with_path
json_get calls json_get_string, json_get_string_with_path, wrap_json_get_string_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path
json_file_get_logical_vec calls json_get
json_update_string calls json_get
json_file_get_double_vec calls json_get
json_file_get_string calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_get_logical_vec_with_path calls json_get
json_file_get_string_vec calls json_get
test_12 calls json_get, json_update
json_file_get_double calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
rename calls json_get, json_update
json_get_integer_vec calls json_get
json_file_get_integer_vec calls json_get
json_get_integer_vec_with_path calls json_get
json_update_logical calls json_get
test_7 calls json_get
json_update_double calls json_get
json_get_double_vec calls json_get
json_file_get_logical calls json_get
json_get_double_vec_with_path calls json_get
json_update_integer calls json_get
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_update_string calls json_update_string
json_update_string_name_ascii calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, wrap_json_update_string, json_update_string_name_ascii, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_integer calls json_update
json_file_update_real calls json_update
test_1 calls json_update
json_file_update_logical calls json_update
json_file_update_string calls json_update
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_real calls json_file_update_real
jf_test_1 calls test_1
wrap_json_file_update_logical calls json_file_update_logical
json_file_update_string_name_ascii calls json_file_update_string
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_file_get_string calls json_file_get_string
wrap_json_file_get_integer calls json_file_get_integer
jf_test_10 calls test_10
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_12 calls test_12
wrap_json_file_get_double calls json_file_get_double
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_update_logical calls json_update_logical
jf_test_7 calls test_7
wrap_json_update_double calls json_update_double
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_update_integer calls json_update_integer