string_to_integer – JSON-Fortran
string_to_integer Function
Source File
Variables
digits ndigits_digits ndigits ierr
Source Code
string_to_integer
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private function string_to_integer(str) result(ival)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str
Return Value integer(kind=IK)
Description
Convert a string into an integer.
History
Jacob Williams : 12/10/2013 : Rewrote routine. Added error checking.
Modified by Izaak Beekman
Note
Replacement for the parse_integer function in the original code.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CDK,len=:), public, allocatable :: digits
integer(kind=IK), public :: ndigits_digits
integer(kind=IK), public :: ndigits
integer(kind=IK), public :: ierr
Source Code
    function string_to_integer(str) result(ival)
    implicit none
    character(kind=CK,len=*),intent(in) :: str
    integer(IK) :: ival
    character(kind=CDK,len=:),allocatable :: digits
    integer(IK) :: ndigits_digits,ndigits,ierr
    if (.not. exception_thrown) then
        ! Compute how many digits we need to read
        ndigits = 2*len_trim(str)
        ndigits_digits = floor(log10(real(ndigits)))+1
        allocate(character(kind=CDK,len=ndigits_digits) :: digits)
        write(digits,'(I0)') ndigits !gfortran will have a runtime error with * edit descriptor here
        ! gfortran bug: '*' edit descriptor for ISO_10646 strings does bad stuff.
        read(str,'(I'//trim(digits)//')',iostat=ierr) ival   !string to integer
        if (ierr/=0) then    !if there was an error
            ival = 0
            call throw_exception('Error in string_to_integer:'//&
                                 ' string cannot be converted to an integer: '//trim(str))
        end if
    else
        ival = 0
    end if
    end function string_to_integer
Call graph
string_to_integer calls throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
parse_number calls string_to_integer
json_get_by_path calls string_to_integer
parse_value calls parse_number, parse_object, parse_array
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
json_parse_file calls parse_value
parse_array calls parse_value
wrap_json_parse_string calls json_parse_string
json_parse calls json_parse_string, json_parse_file, wrap_json_parse_string
test_8 calls json_parse
test_14 calls json_parse
json_file_load calls json_parse
json_file_load_from_string calls json_parse
jf_test_8 calls test_8
jf_test_14 calls test_14
wrap_json_file_load_from_string calls json_file_load_from_string
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
wrap_json_get_by_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
json_get calls json_get_by_path, json_get_integer_with_path, json_get_logical_with_path, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_double_with_path, wrap_json_get_integer_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_string_vec, json_get_logical_vec_with_path, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_string_with_path, wrap_json_get_double_with_path
test_2 calls json_get, json_update
json_file_get_integer_vec calls json_get
json_get_integer_vec_with_path calls json_get
json_file_get_integer calls json_get
json_update_logical calls json_get
json_file_get_string_vec calls json_get
json_update_double calls json_get
json_file_get_double_vec calls json_get
json_get_double_vec calls json_get
json_file_get_logical calls json_get
json_get_double_vec_with_path calls json_get
json_update_integer calls json_get
test_7 calls json_get
json_file_get_logical_vec calls json_get
json_file_get_double calls json_get
json_update_string calls json_get
test_12 calls json_get, json_update
json_get_logical_vec calls json_get
json_get_string_vec calls json_get
json_get_logical_vec_with_path calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_string calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_get_integer_vec calls json_get
rename calls json_get, json_update
jf_test_2 calls test_2
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_integer, json_update_string, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii
json_file_update_string calls json_update
test_1 calls json_update
json_file_update_integer calls json_update
json_file_update_real calls json_update
json_file_update_logical calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_update_double calls json_update_double
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_update_integer calls json_update_integer
jf_test_7 calls test_7
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_double calls json_file_get_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
jf_test_12 calls test_12
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_10 calls test_10
wrap_json_file_get_string calls json_file_get_string
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path
wrap_json_get_array_with_path calls json_get_array_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_double_with_path calls json_get_double_with_path