test_2 – JSON-Fortran
test_2 Subroutine
Source File
Variables
p inp traj p_tmp p_integer_array p_clone iunit name ival ival_clone found
Source Code
test_2
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public subroutine test_2(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
Populate a JSON structure and write it to a file.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p
type(json_value), public, pointer :: inp
type(json_value), public, pointer :: traj
type(json_value), public, pointer :: p_tmp
type(json_value), public, pointer :: p_integer_array
type(json_value), public, pointer :: p_clone
integer, public :: iunit
character(kind=CK,len=:), public, allocatable :: name
integer, public :: ival
integer, public :: ival_clone
logical, public :: found
Source Code
    subroutine test_2(error_cnt)
    !! Populate a JSON structure and write it to a file.
    implicit none
    integer,intent(out) :: error_cnt
    type(json_value),pointer :: p, inp, traj, p_tmp, p_integer_array, p_clone
    integer :: iunit
    character(kind=CK,len=:),allocatable :: name
    integer :: ival,ival_clone
    logical :: found
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 2'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    !root:
    call json_create_object(p,dir//filename2)    ! create the value and associate the pointer
                                                 ! add the file name as the name of the overall structure
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'initialize the structure...'
    !config structure:
    call json_create_object(inp,'inputs')   !an object
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(p, inp)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    !trajectory structure:
    call json_create_array(traj,'trajectory')    !an array
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(p, traj)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'adding some data to structure...'
    !add some variables:
    !input variables:
    call json_add(inp, 't0', 0.1_wp)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'tf', 1.1_wp)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'x0', 9999.000_wp)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'integer_scalar', 1)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'integer_array', [2,4,99])
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'names', ['aaa','bbb','ccc'])
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'logical_scalar', .true.)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(inp, 'logical_vector', [.true., .false., .true.])
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    nullify(inp)
    !trajectory variables:
    call add_variables_to_input(traj, 'Rx', 'km', 'J2000', 'EARTH', [1.0_wp, 2.0_wp, 3.0_wp], error_cnt )
    call add_variables_to_input(traj, 'Ry', 'km', 'J2000', 'EARTH', [10.0_wp, 20.0_wp, 30.0_wp], error_cnt )
    call add_variables_to_input(traj, 'Rz', 'km', 'J2000', 'EARTH', [100.0_wp, 200.0d0, 300.0_wp], error_cnt )
    call add_variables_to_input(traj, 'Vx', 'km/s', 'J2000', 'EARTH', [1.0e-3_wp, 2.0e-3_wp, 3.0e-3_wp], error_cnt )
    call add_variables_to_input(traj, 'Vy', 'km/s', 'J2000', 'EARTH', [2.0e-3_wp, 20.0e-3_wp, 3.0e-3_wp], error_cnt )
    call add_variables_to_input(traj, 'Vz', 'km/s', 'J2000', 'EARTH', [3.0e-3_wp, 30.0e-3_wp, 40.0e-3_wp], error_cnt )
    nullify(traj)
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'writing file '//trim(dir//filename2)//'...'
    open(newunit=iunit, file=dir//filename2, status='REPLACE')
    call json_print(p,iunit)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    close(iunit)
    !test the deep copy routine:
    write(error_unit,'(A)') 'json_clone test'
    call json_clone(p,p_clone)
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '============='
    write(error_unit,'(A)') ' p_clone'
    write(error_unit,'(A)') '============='
    call json_print(p_clone,error_unit)
    write(error_unit,'(A)') '============='
    write(error_unit,'(A)') ''
    if (.not. associated(p)) write(error_unit,'(A)') 'ERROR: p has become unassociated'
    if (.not. associated(p_clone)) write(error_unit,'(A)') 'ERROR: p_clone is not associated'
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !now, change one and verify that they are independent:
        call json_update(p_clone,'inputs.integer_scalar',100,found)
        if (json_failed()) write(error_unit,'(A)') 'json_update Error for p_clone'
        call json_get(p,'inputs.integer_scalar',ival)
        if (json_failed()) write(error_unit,'(A)') 'json_get Error for p'
        call json_get(p_clone,'inputs.integer_scalar',ival_clone)
        if (json_failed()) write(error_unit,'(A)') 'json_get Error for p_clone'
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            if (ival==1 .and. ival_clone==100) then
                write(error_unit,'(A)') 'json_clone ... passed'
            else
                write(error_unit,'(A)') 'Error: ival /= ival_clone'
                error_cnt = error_cnt + 1
            end if
        end if
    end if
    !test some of the pointer routines:
    write(error_unit,'(A)') 'Pointer routine tests'
    call json_get(p,'inputs.integer_array',p_integer_array)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !get parent test:
        call json_get_parent(p_integer_array,p_tmp)  !should be "inputs"
        call json_info(p_tmp,name=name)
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            if (name=='inputs') then
                write(error_unit,'(A)') 'json_get_parent ... passed'
            else
                write(error_unit,'(A)') 'Error: parent should be "inputs", is actually: '//trim(name)
                error_cnt = error_cnt + 1
            end if
        end if
        !get next test:
        call json_get_next(p_integer_array,p_tmp)  !should be "names"
        call json_info(p_tmp,name=name)
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            if (name=='names') then
                write(error_unit,'(A)') 'json_get_next ... passed'
            else
                write(error_unit,'(A)') 'Error: next should be "names", is actually: '//trim(name)
                error_cnt = error_cnt + 1
            end if
        end if
        !get previous test:
        call json_get_previous(p_integer_array,p_tmp)  !should be "integer_scalar"
        call json_info(p_tmp,name=name)
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            if (name=='integer_scalar') then
                write(error_unit,'(A)') 'json_get_previous ... passed'
            else
                write(error_unit,'(A)') 'Error: next should be "integer_scalar", is actually: '//trim(name)
                error_cnt = error_cnt + 1
            end if
        end if
        !get tail test:
        call json_get_tail(p_integer_array,p_tmp)  !should be 99, the last element in the array
        call json_get(p_tmp,ival)
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            if (ival==99) then
                write(error_unit,'(A)') 'json_get_tail ... passed'
            else
                write(error_unit,'(A,1X,I5)') 'Error: tail value should be 99, is actually: ',ival
                error_cnt = error_cnt + 1
            end if
        end if
    end if
    !cleanup:
    call json_destroy(p)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    end subroutine test_2
Call graph
test_2 calls json_print_error_message, add_variables_to_input, json_get_tail, json_create_array, json_info, json_destroy, json_get_previous, json_get_next, json_failed, json_initialize, json_clone, json_print, json_add, json_create_object, json_get_parent, json_update, json_get
json_print_error_message calls json_check_for_errors, json_clear_exceptions
add_variables_to_input calls json_print_error_message, json_failed, json_add, json_create_object
json_create_array calls wrap_json_value_create_array, json_value_create_array
json_info calls json_count
json_destroy calls json_value_destroy
json_initialize calls json_clear_exceptions, throw_exception
json_clone calls json_value_clone_func
json_print calls json_print_1, json_print_2
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_update calls json_update_string, json_update_string_name_ascii, wrap_json_update_double, wrap_json_update_string, json_update_logical, json_update_integer, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_integer, json_update_double
json_get calls wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, json_get_array, wrap_json_get_integer_with_path, wrap_json_get_string_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_by_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_string_vec_with_path
wrap_json_value_create_array calls json_value_create_array, to_unicode
json_value_create_array calls json_value_create, to_array
to_unicode calls to_uni, to_uni_vec
to_array calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_value_clone_func calls json_value_clone_func
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls json_count, throw_exception, json_value_print, integer_to_string, write_it, real_to_string
real_to_string calls compact_real_string
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_integer calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_update_string calls json_info, json_add, json_get, throw_exception, to_string
json_update_string_name_ascii calls to_unicode, json_update_string
wrap_json_update_double calls to_unicode, json_update_double
wrap_json_update_string calls to_unicode, json_update_string
json_update_logical calls json_info, json_add, json_get, throw_exception, to_logical
json_update_integer calls json_info, json_add, json_get, throw_exception, to_integer
json_update_string_val_ascii calls to_unicode, json_update_string
wrap_json_update_logical calls to_unicode, json_update_logical
wrap_json_update_integer calls to_unicode, json_update_integer
json_update_double calls json_info, json_add, json_get, throw_exception, to_double
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_integer, json_get_by_path
json_get_array calls json_count, throw_exception
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_double_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls to_unicode, throw_exception
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_by_path, json_get_string
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls json_count, throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
jf_test_2 calls test_2