test_8 – JSON-Fortran
test_8 Subroutine
Source File
Variables
p newline str str2 str_invalid
Source Code
test_8
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public subroutine test_8(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
read a JSON structure from a string
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p
character(len=*), public, parameter :: newline = achar(10)
character(len=*), public, parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
character(len=*), public, parameter :: str2 = '{ "label": "foo",'//newline//' "value": "bar",'//newline//' "empty_array": [],'//newline//' "empty_object": {}'//newline//'}'
character(len=*), public, parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
Source Code
    subroutine test_8(error_cnt)
    !! read a JSON structure from a string
    implicit none
    integer,intent(out) :: error_cnt
    type(json_value),pointer :: p
    character(len=*),parameter :: newline = achar(10)
    character(len=*),parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
    character(len=*),parameter :: str2 = '{ "label": "foo",'//newline//&
                                         '  "value": "bar",'//newline//&
                                         '  "empty_array": [],'//newline//&
                                         '  "empty_object": {}' //newline//&
                                         '}'
    character(len=*),parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 8 : read JSON from string'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 1:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '{ "part a" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 2:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str2, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part b" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Invalid test:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str_invalid, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
    else
        write(error_unit,'(A)') 'This should have failed!'
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part c" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') '}'
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    end subroutine test_8
Call graph
test_8 calls json_failed, json_initialize, json_destroy, json_parse, json_print, json_print_error_message
json_initialize calls json_clear_exceptions, throw_exception
json_destroy calls json_value_destroy
json_parse calls wrap_json_parse_string, json_parse_file, json_parse_string
json_print calls json_print_1, json_print_2
json_print_error_message calls json_clear_exceptions, json_check_for_errors
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_value_destroy calls json_value_destroy, destroy_json_data
wrap_json_parse_string calls to_unicode, json_parse_string
json_parse_file calls json_initialize, throw_exception, annotate_invalid_json, parse_value, json_value_create
json_parse_string calls json_initialize, annotate_invalid_json, parse_value, json_value_create
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
parse_value calls throw_exception, parse_array, parse_string, to_logical, pop_char, push_char, to_null, to_array, to_object, parse_for_chars, to_string, parse_object, parse_number
parse_array calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, json_add
parse_string calls throw_exception, pop_char, valid_json_hex
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
to_array calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
to_string calls destroy_json_data
parse_object calls json_destroy, throw_exception, parse_value, json_value_create, parse_string, pop_char, parse_object, json_add
parse_number calls throw_exception, pop_char, push_char, to_integer, to_double, string_to_integer, string_to_double
json_add calls wrap_json_value_add_integer, wrap_json_value_add_string, json_value_add_logical_vec, json_value_add_integer_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_logical, json_value_add_integer, json_value_add_double_vec, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, json_value_add_string_val_ascii, json_value_add_double, wrap_json_value_add_double, json_value_add_logical, json_value_add_string, json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_name_ascii, json_value_add_string_vec_val_ascii, json_value_add_member
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_integer_vec calls json_value_create, to_array, json_add
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, to_array, json_add
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
to_integer calls destroy_json_data
to_double calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls throw_exception, integer_to_string, json_value_print, write_it, real_to_string, json_count
real_to_string calls compact_real_string
jf_test_8 calls test_8