test_7 – JSON-Fortran
test_7 Subroutine
Source File
Variables
root a b c d e e1 e2 escaped_string p found strvec string
Source Code
test_7
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public subroutine test_7(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
Indent test
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: root
type(json_value), public, pointer :: a
type(json_value), public, pointer :: b
type(json_value), public, pointer :: c
type(json_value), public, pointer :: d
type(json_value), public, pointer :: e
type(json_value), public, pointer :: e1
type(json_value), public, pointer :: e2
type(json_value), public, pointer :: escaped_string
type(json_value), public, pointer :: p
logical, public :: found
character(kind=CK,len=1), public, dimension(:), allocatable :: strvec
character(kind=CK,len=:), public, allocatable :: string
Source Code
    subroutine test_7(error_cnt)
    !! Indent test
    implicit none
    integer,intent(out) :: error_cnt
    type(json_value),pointer :: root,a,b,c,d,e,e1,e2,escaped_string,p
    logical :: found
    character(kind=CK,len=1), dimension(:), allocatable :: strvec
    character(kind=CK,len=:), allocatable :: string
    found=.false.
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 7 : indent test'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
!-----------------------
! jsonlint indention is
!-----------------------
!{
!    "a": {
!        "ints": [
!            1,
!            2,
!            3
!        ],
!        "chars": [
!            "a",
!            "b",
!            "c"
!        ]
!    },
!    "b": {
!        "c": {
!            "val1": 1066
!        }
!    },
!    "d": {
!        "val2": 1815
!    },
!    "array": [
!        {
!            "int1": 1
!        },
!        {
!            "int1": 1,
!            "int2": 2
!        }
!    ]
!    "escaped string": "\\\/\b\f\n\r\t"
!}
    !create a json structure:
    call json_create_object(root,'root')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(a,'a')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(a,'ints', [1,2,3])
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(b,'b')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(a,'chars', ['a','b','c'])
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_get_child(a,'chars',p)
    call json_get(p,strvec)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(c,'c')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(c,'val1', 1066)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(d,'d')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(d,'val2', 1815)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_array(e,'array')   !objects in an array
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(e1,'')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(e1,'int1', 1)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_create_object(e2,'')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(e2,'int1', 1)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(e2,'int2', 2)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(e,e1)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(e,e2)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,a)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,b)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(b,c)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,d)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,e)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,'escaped string',&
         '\/'//&
         achar(8)//&
         achar(12)//&
         achar(10)//&
         achar(13)//&
         achar(9))
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(root,'wacky string',['trim   ','  and  ',' adjust','   left'],&
         trim_str=.true.,adjustl_str=.true.)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    nullify(a)  !don't need these anymore
    nullify(b)
    nullify(c)
    nullify(d)
    nullify(e)
    nullify(e1)
    nullify(e2)
    nullify(escaped_string)
    call json_print(root,output_unit)  !print to the console
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    ! look for the 'escaped string' entry
    call json_get(root,'escaped string',escaped_string,found)
    if (json_failed() .or. .not. found) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_get(escaped_string,string)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') "Fetched unescaped 'escaped string': "//string
    ! remove the escaped string entry
    if (found) call json_remove(escaped_string,destroy=.true.)
    call json_print(root,error_unit)  !print to stderr
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(root)  !cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    end subroutine test_7
Call graph
test_7 calls json_print_error_message, json_failed, json_get_child, json_destroy, json_initialize, json_get, json_print, json_add, json_remove, json_create_object, json_create_array
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
json_destroy calls json_value_destroy
json_initialize calls json_clear_exceptions, throw_exception
json_get calls wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, json_get_array, wrap_json_get_integer_with_path, wrap_json_get_string_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_by_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_string_vec_with_path
json_print calls json_print_1, json_print_2
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
json_remove calls json_value_remove
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_create_array calls wrap_json_value_create_array, json_value_create_array
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars, to_unicode
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_value_destroy calls json_value_destroy, destroy_json_data
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_integer, json_get_by_path
json_get_array calls throw_exception, json_count
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_double_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
json_get_by_path calls json_get_child, json_clear_exceptions, throw_exception, string_to_integer
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, to_unicode
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_by_path, json_get_string
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
string_to_integer calls throw_exception
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls throw_exception, json_count, json_value_print, integer_to_string, write_it, real_to_string
real_to_string calls compact_real_string
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data
json_value_remove calls json_value_destroy
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
wrap_json_value_create_array calls to_unicode, json_value_create_array
json_value_create_array calls json_value_create, to_array
jf_test_7 calls test_7