test_10 – JSON-Fortran
test_10 Subroutine
Source File
Variables
str_vec f f2 p str name found lval var_type n_children json_str
Source Code
test_10
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public subroutine test_10(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
Test some of the lesser-used features of the library
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=256), public, dimension(:), allocatable :: str_vec
type(json_file), public :: f
type(json_file), public :: f2
type(json_value), public, pointer :: p
character(kind=CK,len=:), public, allocatable :: str
character(kind=CK,len=:), public, allocatable :: name
logical, public :: found
logical, public :: lval
integer, public :: var_type
integer, public :: n_children
character(kind=CDK,len=*), public, parameter :: json_str = '{ "blah": 123 }'
Source Code
    subroutine test_10(error_cnt)
    !! Test some of the lesser-used features of the library
    implicit none
    integer,intent(out) :: error_cnt
    character(kind=CK,len=256),dimension(:),allocatable :: str_vec
    type(json_file) :: f,f2
    type(json_value),pointer :: p
    character(kind=CK,len=:),allocatable :: str,name
    logical :: found,lval
    integer :: var_type,n_children
    character(kind=CDK,len=*),parameter :: json_str = '{ "blah": 123 }'
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 10 '
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'Loading file: '//trim(filename)//'...'
    call f%load_file(dir//filename)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'json_file_move_pointer...'
    call f2%move(f)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') 'json_file_load_from_string...'
    call f%load_from_string(json_str)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') 'json_file_print_to_string...'
    call f%print_to_string(str)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') 'json_file_variable_info...'
    call f%info('blah',found,var_type,n_children)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !also make sure the values are correct:
        if (var_type==json_integer .and. n_children==0) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error invalid values:',var_type,n_children
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_file_get_logical...'
    call f2%get('data(1).tf1',lval,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !also make sure the values are correct:
        if (found .and. lval) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: incorrect result.'
            error_cnt = error_cnt + 1
        end if
    end if
    ! json_file_get_logical_vec .... [add this]
    write(error_unit,'(A)') 'json_file_get_string_vec...'
    call f2%get('files',str_vec,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !also make sure the values are correct:
        if (found .and. size(str_vec)==5 .and. &
            str_vec(1)=='..\path\to\files\file1.txt') then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: incorrect result: '//trim(str_vec(1))
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_file_update_logical [variable present]...'
    call f2%update('data(1).tf1',.false.,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_file_update_logical [variable not present]...'
    call f2%update('new_logical',.true.,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') 'json_file_update_real [variable present]...'
    call f2%update('data[2].real',100.0d0,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_file_update_real [variable not present]...'
    call f2%update('new_real',1776.0d0,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    write(error_unit,'(A)') 'json_file_update_string [variable present]...'
    call f2%update('version.string','10.0.0',found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_file_update_string [variable not present]...'
    call f2%update('new_string','foo',found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    !--------------------------------
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'json_file_get_integer...'
    call f2%get('$',p,found)  !get root
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
            write(error_unit,'(A)') 'json_info...'
            call json_info(p,var_type,n_children,name)
            if (json_failed()) then
                call json_print_error_message(error_unit)
                error_cnt = error_cnt + 1
            else
                write(error_unit,'(A)') '...success'
            end if
            write(error_unit,'(A)') 'json_remove_if_present...'
            call json_remove_if_present(p,'version.patch')
            if (json_failed()) then
                call json_print_error_message(error_unit)
                error_cnt = error_cnt + 1
            else
                write(error_unit,'(A)') '...success'
            end if
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_update_logical...'
    call json_update(p,'data(1).tf1',.true.,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_update_double...'
    call json_update(p,'data(2).real',-1.0d0,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_get_logical...'
    call json_get(p,'data(1).tf1',lval,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        if (found) then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: variable was not there.'
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_get_string_vec...'
    call json_get(p,'files',str_vec,found)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        !also make sure the values are correct:
        if (found .and. size(str_vec)==5 .and. &
            str_vec(1)=='..\path\to\files\file1.txt') then
            write(error_unit,'(A)') '...success'
        else
            write(error_unit,'(A)') 'Error: incorrect result: '//trim(str_vec(1))
            error_cnt = error_cnt + 1
        end if
    end if
    write(error_unit,'(A)') 'json_create...'
    write(error_unit,'(A)') 'json_create_logical...'; call json_destroy(p); call json_create_logical(p,.true.,'foo')
    write(error_unit,'(A)') 'json_create_integer...'; call json_destroy(p); call json_create_integer(p,1000,'foo')
    write(error_unit,'(A)') 'json_create_double ...'; call json_destroy(p); call json_create_double (p,9.0d0,'foo')
    write(error_unit,'(A)') 'json_create_string ...'; call json_destroy(p); call json_create_string (p,'foo','bar')
    write(error_unit,'(A)') 'json_create_null   ...'; call json_destroy(p); call json_create_null   (p,'foo')
    write(error_unit,'(A)') 'json_create_object ...'; call json_destroy(p); call json_create_object (p,'foo')
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') '...success'
    end if
    !--------------------------------
    !cleanup:
    !call f%destroy()   !WARNING: causing "pointer being freed was not allocated" errors.... need to investigate
    !call f2%destroy()
    end subroutine test_10
Call graph
test_10 calls json_info, json_remove_if_present, json_create_string, json_initialize, json_get, json_create_logical, json_destroy, json_create_double, json_failed, json_create_null, json_create_object, json_print_error_message, json_update, json_create_integer
json_info calls json_count
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
json_create_string calls wrap_json_value_create_string, json_value_create_string
json_initialize calls json_clear_exceptions, throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, wrap_json_get_string_vec_with_path, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_array, wrap_json_get_double_vec_with_path, json_get_logical, wrap_json_get_string_with_path, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_by_path
json_create_logical calls wrap_json_value_create_logical, json_value_create_logical
json_destroy calls json_value_destroy
json_create_double calls wrap_json_value_create_double, json_value_create_double
json_create_null calls wrap_json_value_create_null, json_value_create_null
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_update calls json_update_string, wrap_json_update_double, json_update_string_name_ascii, json_update_logical, json_update_string_val_ascii, wrap_json_update_string, wrap_json_update_integer, json_update_integer, json_update_double, wrap_json_update_logical
json_create_integer calls wrap_json_value_create_integer, json_value_create_integer
json_value_remove_if_present calls json_get, json_remove
wrap_json_value_remove_if_present calls json_value_remove_if_present, to_unicode
json_remove calls json_value_remove
json_value_remove calls json_value_destroy
json_value_destroy calls json_value_destroy, destroy_json_data
to_unicode calls to_uni, to_uni_vec
wrap_json_value_create_string calls to_unicode, json_value_create_string
json_value_create_string calls json_value_create, to_string
to_string calls destroy_json_data
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_double_vec_with_path calls json_get
json_get_array calls json_count, throw_exception
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls to_unicode, throw_exception
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_string, json_get_by_path
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_integer, json_get_by_path
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls json_count, throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
wrap_json_value_create_logical calls to_unicode, json_value_create_logical
json_value_create_logical calls json_value_create, to_logical
to_logical calls destroy_json_data
wrap_json_value_create_double calls to_unicode, json_value_create_double
json_value_create_double calls json_value_create, to_double
to_double calls destroy_json_data
wrap_json_value_create_null calls to_unicode, json_value_create_null
json_value_create_null calls json_value_create, to_null
to_null calls destroy_json_data
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_update_string calls json_info, json_get, to_string, throw_exception, json_add
wrap_json_update_double calls to_unicode, json_update_double
json_update_string_name_ascii calls to_unicode, json_update_string
json_update_logical calls json_info, json_get, throw_exception, to_logical, json_add
json_update_string_val_ascii calls to_unicode, json_update_string
wrap_json_update_string calls to_unicode, json_update_string
wrap_json_update_integer calls to_unicode, json_update_integer
json_update_integer calls json_info, json_get, throw_exception, json_add, to_integer
json_update_double calls json_info, json_get, throw_exception, to_double, json_add
wrap_json_update_logical calls to_unicode, json_update_logical
json_add calls wrap_json_value_add_integer, wrap_json_value_add_string, json_value_add_logical_vec, json_value_add_integer_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_logical, json_value_add_integer, json_value_add_double_vec, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, json_value_add_string_val_ascii, json_value_add_double, wrap_json_value_add_double, json_value_add_logical, json_value_add_string, json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_name_ascii, json_value_add_string_vec_val_ascii, json_value_add_member
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
json_value_add_logical_vec calls json_value_create, json_add, to_array
json_value_add_integer_vec calls json_value_create, json_add, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, json_add, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_value_create, to_double, json_add
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
json_value_add_string_vec calls json_value_create, json_add, to_array
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
to_array calls destroy_json_data
to_integer calls destroy_json_data
wrap_json_value_create_integer calls to_unicode, json_value_create_integer
json_value_create_integer calls json_value_create, to_integer
jf_test_10 calls test_10