test_1 – JSON-Fortran
test_1 Subroutine
Source File
Variables
json ival cval rval found p
Source Code
test_1
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public subroutine test_1(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
Read a sample JSON file and retrieve some data from it
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_file), public :: json
integer, public :: ival
character(kind=CK,len=:), public, allocatable :: cval
real(kind=wp), public :: rval
logical, public :: found
type(json_value), public, pointer :: p
Source Code
    subroutine test_1(error_cnt)
    !! Read a sample JSON file and retrieve some data from it
    implicit none
    integer,intent(out) :: error_cnt
    type(json_file) :: json    !the JSON structure read from the file:
    integer :: ival
    character(kind=CK,len=:),allocatable :: cval
    real(wp) :: rval
    logical :: found
    type(json_value),pointer :: p
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
      call json_print_error_message(error_unit)
      error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   TEST 1'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    ! parse the json file:
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'parsing file '//dir//filename1
    call json%load_file(filename = dir//filename1)
    if (json_failed()) then    !if there was an error reading the file
      call json_print_error_message(error_unit)
      error_cnt = error_cnt + 1
    else
      ! print the parsed data to the console
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') 'printing the file...'
      write(output_unit,'(A)') '{ "part a" :' !Wrap 3 outputs to make stdout valid json
      call json%print_file()
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      ! extract data from the parsed value
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') 'get some data from the file...'
      write(error_unit,'(A)') ''
      call json%get('version.svn', ival)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A,I5)') 'version.svn = ',ival
      end if
      write(error_unit,'(A)') ''
      call json%get('data(1).array(2)', cval)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'data(1).array(2) = '//trim(cval)
      end if
      write(error_unit,'(A)') ''
      call json%get('files(1)', cval)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'files(1) = '//trim(cval)
      end if
      write(error_unit,'(A)') ''
      call json%get('files(2)', cval)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'files(2) = '//trim(cval)
      end if
      write(error_unit,'(A)') ''
      call json%get('files(3)', cval)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'files(3) = '//trim(cval)
      end if
      write(error_unit,'(A)') ''
      call json%get('data(2).real', rval)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A,E30.16)') 'data(2).real = ',rval
      end if
      write(error_unit,'(A)') ''
      call json%get('files[4]', cval)      !has hex characters
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'files[4] = '//trim(cval)
      end if
      write(error_unit,'(A)') ''
      call json%get('files[5]', cval)      !string with spaces and no escape characters
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      else
        write(error_unit,'(A)') 'files[5] = '//trim(cval)
      end if
      !
      ! Test of values that aren't there:
      ! Note: when using the "found" output, the exceptions are cleared automatically.
      !
      write(error_unit,'(A)') ''
      call json%get('files[10]', cval, found)      !value that isn't there
      if (.not. found) then
        write(error_unit,'(A)') 'files[10] not in file.'
      else
        write(error_unit,'(1x,A)') 'files[10] = '//trim(cval)
        error_cnt = error_cnt + 1
      end if
      write(error_unit,'(A)') ''
      call json%get('version.blah', ival, found)      !value that isn't there
      if (.not. found) then
        write(error_unit,'(A)') 'version.blah not in file.'
      else
        write(error_unit,'(A)') 'version.blah = ',ival
        error_cnt = error_cnt + 1
      end if
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') ' Test removing data from the json structure:'
      call json%get('files', p)         !in the middle of a list
      call json_remove(p)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      call json%get('data(1).array', p)   !at the end of a list
      call json_remove(p)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      call json%get('data(2).number', p)  !at the beginning of a list
      call json_remove(p)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') 'printing the modified structure...'
      write(output_unit,'(A)') ', "part b" : '
      call json%print_file()
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') ' Test replacing data from the json structure:'
      call json%get('data(1)', p)
      call json_update(p,'name','Cuthbert',found)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      !call json%get('data(2)', p)
      !call json_update(p,'real',[1.0_wp, 2.0_wp, 3.0_wp],found)   !don't have one like this yet...
      !use the json_file procedure to update a variable:
      call json%update('version.svn',999,found)
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
      write(error_unit,'(A)') ''
      write(error_unit,'(A)') 'printing the modified structure...'
      write(output_unit,'(A)') ', "part c" : '
      call json%print_file()
      write(output_unit,'(A)') '}'
      if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
      end if
    end if
    ! clean up
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'destroy...'
    call json%destroy()
    if (json_failed()) then
      call json_print_error_message(error_unit)
      error_cnt = error_cnt + 1
    end if
    end subroutine test_1
Call graph
test_1 calls json_update, json_initialize, json_remove, json_print_error_message, json_failed
json_update calls json_update_string, wrap_json_update_double, json_update_string_name_ascii, json_update_logical, json_update_string_val_ascii, wrap_json_update_string, wrap_json_update_integer, json_update_integer, json_update_double, wrap_json_update_logical
json_initialize calls throw_exception, json_clear_exceptions
json_remove calls json_value_remove
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_update_string calls json_add, json_info, throw_exception, json_get, to_string
wrap_json_update_double calls json_update_double, to_unicode
json_update_string_name_ascii calls json_update_string, to_unicode
json_update_logical calls json_add, json_info, throw_exception, json_get, to_logical
json_update_string_val_ascii calls json_update_string, to_unicode
wrap_json_update_string calls json_update_string, to_unicode
wrap_json_update_integer calls json_update_integer, to_unicode
json_update_integer calls json_add, json_info, throw_exception, json_get, to_integer
json_update_double calls json_add, json_info, throw_exception, json_get, to_double
wrap_json_update_logical calls json_update_logical, to_unicode
json_add calls wrap_json_value_add_integer, wrap_json_value_add_string, json_value_add_logical_vec, json_value_add_integer_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_logical, json_value_add_integer, json_value_add_double_vec, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, json_value_add_string_val_ascii, json_value_add_double, wrap_json_value_add_double, json_value_add_logical, json_value_add_string, json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_name_ascii, json_value_add_string_vec_val_ascii, json_value_add_member
json_info calls json_count
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, wrap_json_get_string_vec_with_path, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_array, wrap_json_get_double_vec_with_path, json_get_logical, wrap_json_get_string_with_path, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_by_path
to_string calls destroy_json_data
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
wrap_json_value_add_string calls json_value_add_string, to_unicode
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string calls json_add, to_string, json_value_create, escape_string
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
to_unicode calls to_uni, to_uni_vec
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_double_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_logical_with_path calls throw_exception, json_get_logical, json_get_by_path, json_clear_exceptions
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, to_unicode
json_get_array_with_path calls throw_exception, json_get_array, json_get_by_path, json_clear_exceptions
json_get_string_with_path calls throw_exception, json_get_string, json_get_by_path, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls throw_exception, json_get_integer, json_get_by_path, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_by_path calls throw_exception, json_clear_exceptions, json_get_child, string_to_integer
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
json_value_remove calls json_value_destroy
json_value_destroy calls destroy_json_data, json_value_destroy
jf_test_1 calls test_1