to_uni_vec – JSON-Fortran
to_uni_vec Function
Izaak Beekman
Source File
Source Code
to_uni_vec
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
private purefunction to_uni_vec(str)
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in), dimension(:) :: str
Return Value character(kind=CK,len=len(str)), dimension(size(str))
Description
Convert array of strings to unicode (CDK to CK).
Note
JW: may be able to remove this by making to_uni PURE ELEMENTAL ?
Called By
Source Code
    pure function to_uni_vec(str)
    implicit none
    character(kind=CDK,len=*), dimension(:), intent(in)   :: str
    character(kind=CK,len=len(str)), dimension(size(str)) :: to_uni_vec
    to_uni_vec = str
    end function to_uni_vec
Call graph
to_unicode calls to_uni_vec
default_comp_ucs4 calls to_unicode
wrap_json_file_update_string calls to_unicode, json_file_update_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_file_get_string_vec calls to_unicode, json_file_get_string_vec
wrap_json_value_create_object calls to_unicode
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_file_get_double calls to_unicode, json_file_get_double
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
wrap_json_file_get_string calls to_unicode, json_file_get_string
wrap_json_value_create_null calls to_unicode
wrap_json_file_get_double_vec calls to_unicode, json_file_get_double_vec
wrap_json_file_get_integer_vec calls to_unicode, json_file_get_integer_vec
wrap_json_update_double calls to_unicode, json_update_double
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
wrap_json_parse_string calls to_unicode, json_parse_string
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_file_update_string_val_ascii calls to_unicode, json_file_update_string
wrap_json_file_get_logical_vec calls to_unicode, json_file_get_logical_vec
wrap_json_file_update_logical calls to_unicode, json_file_update_logical
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
wrap_json_value_create_string calls to_unicode
wrap_json_file_update_integer calls to_unicode, json_file_update_integer
wrap_json_file_get_object calls to_unicode, json_file_get_object
json_update_string_val_ascii calls to_unicode, json_update_string
wrap_json_update_integer calls to_unicode, json_update_integer
wrap_json_value_create_integer calls to_unicode
wrap_json_throw_exception calls to_unicode
json_update_string_name_ascii calls to_unicode, json_update_string
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
wrap_json_file_get_logical calls to_unicode, json_file_get_logical
wrap_json_value_create_double calls to_unicode
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
wrap_json_update_string calls to_unicode, json_update_string
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_file_update_real calls to_unicode, json_file_update_real
wrap_json_file_get_integer calls to_unicode, json_file_get_integer
wrap_json_value_create_logical calls to_unicode
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_file_load_from_string calls to_unicode, json_file_load_from_string
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_remove_if_present calls to_unicode, json_value_remove_if_present
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_string calls to_unicode, throw_exception
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
ucs4_join_default calls to_unicode
ucs4_comp_default calls to_unicode
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
default_join_ucs4 calls to_unicode
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_create_array calls to_unicode
json_file_update_string_name_ascii calls to_unicode, json_file_update_string
wrap_json_file_variable_info calls to_unicode
wrap_json_update_logical calls to_unicode, json_update_logical
operator(==) calls default_comp_ucs4, ucs4_comp_default
json_add calls wrap_json_value_add_double, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, wrap_json_value_add_logical, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, wrap_json_value_add_string, json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_vec_val_ascii, json_value_add_integer_vec, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_double, json_value_add_string, json_value_add_string_vec, json_value_add_logical
test_2 calls json_add, add_variables_to_input, json_update, json_create_object, json_get, json_initialize, json_print, json_create_array
parse_array calls json_add, parse_value, throw_exception
json_update_integer calls json_add, json_get, throw_exception
json_update_double calls json_add, json_get, throw_exception
json_value_add_integer_vec calls json_add
json_value_add_integer calls json_add
test_12 calls json_add, json_update, json_create_object, json_get, json_initialize, json_print
json_update_logical calls json_add, json_get, throw_exception
json_value_add_double_vec calls json_add
json_value_add_logical_vec calls json_add
add_variables_to_input calls json_add, json_create_object
test_4 calls json_add, json_create_object, json_initialize, json_print, json_print_to_string
json_update_string calls json_add, json_get, throw_exception
json_value_add_double calls json_add
parse_object calls json_add, parse_object, parse_value, throw_exception, parse_string
json_value_add_string calls json_add
json_value_add_string_vec calls json_add
test_7 calls json_add, json_create_object, json_get, json_get_child, json_initialize, json_print, json_create_array
json_value_add_logical calls json_add
jf_test_2 calls test_2
parse_value calls parse_array, parse_object, throw_exception, parse_number, parse_string, push_char, parse_for_chars
json_parse_string calls parse_value, json_initialize
json_parse_file calls parse_value, throw_exception, json_initialize
json_parse calls wrap_json_parse_string, json_parse_string, json_parse_file
test_8 calls json_parse, json_initialize, json_print
test_14 calls json_parse, json_initialize, json_print
json_file_load calls json_parse
json_file_load_from_string calls json_parse
jf_test_8 calls test_8
jf_test_14 calls test_14
json_update calls wrap_json_update_double, json_update_string_val_ascii, wrap_json_update_integer, json_update_string_name_ascii, wrap_json_update_string, wrap_json_update_logical, json_update_integer, json_update_double, json_update_logical, json_update_string
json_file_update_string calls json_update
test_10 calls json_update, json_create_object, json_get, json_remove_if_present, json_create_null, json_create_string, json_create_integer, json_initialize, json_create_double, json_create_logical
test_1 calls json_update, json_initialize
json_file_update_integer calls json_update
json_file_update_real calls json_update
rename calls json_update, json_get
json_file_update_logical calls json_update
jf_test_10 calls test_10
jf_test_1 calls test_1
jf_test_12 calls test_12
jf_test_4 calls test_4
jf_test_7 calls test_7
json_create_object calls wrap_json_value_create_object
json_get calls wrap_json_get_string_vec_with_path, wrap_json_get_double_with_path, wrap_json_get_array_with_path, wrap_json_get_by_path, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_with_path, json_get_string, wrap_json_get_integer_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_string_vec, json_get_logical_vec_with_path, json_get_string_vec_with_path, json_get_integer_vec, json_get_by_path, json_get_integer_with_path, json_get_logical_with_path, json_get_array_with_path, json_get_string_with_path, json_get_double_with_path, json_get_double, json_get_logical, json_get_integer, json_get_array
json_file_get_integer_vec calls json_get
json_get_integer_vec_with_path calls json_get
json_file_get_integer calls json_get
json_file_get_string_vec calls json_get
json_file_get_double_vec calls json_get
json_get_double_vec calls json_get
json_file_get_logical calls json_get
json_get_double_vec_with_path calls json_get
json_file_get_logical_vec calls json_get
json_file_get_double calls json_get
json_get_logical_vec calls json_get
json_get_string_vec calls json_get
json_get_logical_vec_with_path calls json_get
json_file_get_string calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_get_integer_vec calls json_get
json_remove_if_present calls wrap_json_value_remove_if_present, json_value_remove_if_present
json_create_null calls wrap_json_value_create_null
json_get_child calls wrap_json_value_get_by_name_chars, json_value_get_by_index, json_value_get_by_name_chars
json_get_by_path calls json_get_child, throw_exception, string_to_integer
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path, throw_exception, json_get_integer
json_get_logical_with_path calls json_get_by_path, throw_exception, json_get_logical
json_get_array_with_path calls json_get_by_path, throw_exception, json_get_array
json_get_string_with_path calls json_get_string, json_get_by_path, throw_exception
json_get_double_with_path calls json_get_by_path, throw_exception, json_get_double
json_create_string calls wrap_json_value_create_string
json_create_integer calls wrap_json_value_create_integer
throw_exception calls wrap_json_throw_exception
json_get_double calls throw_exception
parse_number calls throw_exception, string_to_integer, string_to_double, push_char
json_print_2 calls throw_exception, json_print
string_to_integer calls throw_exception
parse_string calls throw_exception
string_to_double calls throw_exception
json_get_logical calls throw_exception
json_print_1 calls throw_exception, json_value_print
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception
json_file_print_1 calls throw_exception, json_value_print
json_value_print calls throw_exception, json_value_print
json_file_print_2 calls throw_exception
json_get_integer calls throw_exception
json_initialize calls throw_exception
push_char calls throw_exception
json_file_move_pointer calls throw_exception
json_get_array calls throw_exception
parse_for_chars calls throw_exception
json_print calls json_print_2, json_print_1
json_value_to_string calls json_value_print
json_file_print_to_console calls json_value_print
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string
test_13 calls json_initialize
test_9 calls json_initialize
test_6 calls json_initialize
test_5 calls json_initialize
test_11 calls json_initialize
test_3 calls json_initialize
jf_test_13 calls test_13
jf_test_9 calls test_9
jf_test_6 calls test_6
jf_test_5 calls test_5
jf_test_11 calls test_11
jf_test_3 calls test_3
json_create_double calls wrap_json_value_create_double
json_create_logical calls wrap_json_value_create_logical
operator(SLASHSLASH) calls ucs4_join_default, default_join_ucs4
json_create_array calls wrap_json_value_create_array