unescape_string – JSON-Fortran
unescape_string Subroutine
Source File
private subroutine unescape_string(str_in, str_out)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str_in
string as stored in a json_value
character(kind=CK,len=:), intent(out), allocatable :: str_out
decoded string
Description
Remove the escape characters from a JSON string and return it.
The escaped characters are denoted by the '' character:
    '\"'        quotation mark
    '\\'        reverse solidus
    '\/'        solidus
    '\b'        backspace
    '\f'        formfeed
    '\n'        newline (LF)
    '\r'        carriage return (CR)
    '\t'        horizontal tab
    '\uXXXX'    4 hexadecimal digits
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
counter
integer, public :: n
length of str_in
integer, public :: m
length of str_out
character(kind=CK,len=1), public :: c
for scanning each character in string
Source Code
    subroutine unescape_string(str_in, str_out)
    implicit none
    character(kind=CK,len=*),intent(in)              :: str_in  !! string as stored in a [[json_value]]
    character(kind=CK,len=:),allocatable,intent(out) :: str_out !! decoded string
    integer :: i   !! counter
    integer :: n   !! length of str_in
    integer :: m   !! length of str_out
    character(kind=CK,len=1) :: c  !! for scanning each character in string
    if (scan(str_in,backslash)>0) then
        !there is at least one escape character, so process this string:
        n = len(str_in)
        str_out = repeat(space,n) !size the output string (will be trimmed later)
        m = 0  !counter in str_out
        i = 0  !counter in str_in
        do
            i = i + 1
            if (i>n) exit ! finished
            c = str_in(i:i) ! get next character in the string
            if (c == backslash) then
                if (i<n) then
                    i = i + 1
                    c = str_in(i:i) !character after the escape
                    if (any(c == [quotation_mark,backslash,slash, &
                         to_unicode(['b','f','n','r','t'])])) then
                        select case(c)
                        case (quotation_mark,backslash,slash)
                            !use d as is
                        case (CK_'b')
                             c = bspace
                        case (CK_'f')
                             c = formfeed
                        case (CK_'n')
                             c = newline
                        case (CK_'r')
                             c = carriage_return
                        case (CK_'t')
                             c = horizontal_tab
                        end select
                        m = m + 1
                        str_out(m:m) = c
                    else if (c == 'u') then !expecting 4 hexadecimal digits after
                                            !the escape character    [\uXXXX]
                        !for now, we are just returning them as is
                        ![not checking to see if it is a valid hex value]
                        !
                        ! Example:
                        !   123456
                        !   \uXXXX
                        if (i+4<=n) then
                            m = m + 1
                            str_out(m:m+5) = str_in(i-1:i+4)
                            i = i + 4
                            m = m + 5
                        else
                            call throw_exception('Error in json_get_string:'//&
                                                 ' Invalid hexadecimal sequence'//&
                                                 ' in string: '//str_in(i-1:))
                            str_out = ''
                            return
                        end if
                    else
                        !unknown escape character
                        call throw_exception('Error in json_get_string:'//&
                                             ' unknown escape sequence in string "'//&
                                             trim(str_in)//'" ['//backslash//c//']')
                        str_out = ''
                        return
                    end if
                else
                    !an escape character is the last character in
                    ! the string [this may not be valid syntax,
                    ! but just keep it]
                    m = m + 1
                    str_out(m:m) = c
                end if
            else
                m = m + 1
                str_out(m:m) = c
            end if
        end do
        !trim trailing space:
        str_out = str_out(1:m)
    else
        !there are no escape characters, so return as is:
        str_out = str_in
    end if
    end subroutine unescape_string
Call graph
unescape_string calls to_unicode, throw_exception
to_unicode calls to_uni_vec, to_uni
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_string calls unescape_string
json_get_string_with_path calls json_get_string
wrap_json_get_string_with_path calls json_get_string_with_path
json_get calls json_get_string, json_get_string_with_path, wrap_json_get_string_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path
json_get_string_vec calls json_get
test_7 calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_file_get_double calls json_get
json_get_integer_vec calls json_get
test_12 calls json_get, json_update
json_get_integer_vec_with_path calls json_get
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_update_string calls json_get
json_get_double_vec calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
json_file_get_logical calls json_get
rename calls json_get, json_update
json_update_integer calls json_get
json_get_logical_vec calls json_get
json_file_get_string calls json_get
json_file_get_logical_vec calls json_get
json_file_get_integer calls json_get
test_2 calls json_get, json_update
json_get_logical_vec_with_path calls json_get
json_file_get_string_vec calls json_get
json_file_get_double_vec calls json_get
test_10 calls json_get, json_remove_if_present, json_update
jf_test_7 calls test_7
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_file_get_double calls json_file_get_double
jf_test_12 calls test_12
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_string, json_update_double, json_update_integer, wrap_json_update_logical, wrap_json_update_string, json_update_string_name_ascii, json_update_string_val_ascii, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
test_1 calls json_update
json_file_update_logical calls json_update
json_file_update_real calls json_update
json_file_update_integer calls json_update
json_file_update_string_name_ascii calls json_file_update_string
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_update_string calls json_update_string
json_update_string_name_ascii calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_string calls json_file_get_string
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
jf_test_2 calls test_2
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_file_get_double_vec calls json_file_get_double_vec
jf_test_10 calls test_10