json_update – JSON-Fortran
json_update Interface
Source File
Module Procedures
json_update_logical wrap_json_update_logical json_update_double wrap_json_update_double json_update_integer wrap_json_update_integer json_update_string wrap_json_update_string json_update_string_name_ascii json_update_string_val_ascii
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public interface json_update
These are like json_add, except if a child with the same name is already present, then its value is simply updated. Note that currently, these only work for scalar variables. These routines can also change the variable's type (but an error will be thrown if the existing variable is not a scalar).
Note
It should not be used to change the type of a variable in an array, or it may result in an invalid JSON file.
Calls
Called By
Module Procedures
private subroutine json_update_logical(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
logical(kind=LK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_logical(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
logical(kind=LK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_logical, where "name" is kind=CDK.
private subroutine json_update_double(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
real(kind=RK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_double(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
real(kind=RK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_double, where "name" is kind=CDK.
private subroutine json_update_integer(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_integer(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_integer, where "name" is kind=CDK.
private subroutine json_update_string(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_string(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "name" and "value" are kind=CDK.
private subroutine json_update_string_name_ascii(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "name" is kind=CDK.
private subroutine json_update_string_val_ascii(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "val" is kind=CDK.
Call graph
json_update calls json_update_string, wrap_json_update_double, json_update_string_name_ascii, json_update_logical, json_update_string_val_ascii, wrap_json_update_string, wrap_json_update_integer, json_update_integer, json_update_double, wrap_json_update_logical
json_update_string calls json_add, json_info, throw_exception, json_get, to_string
wrap_json_update_double calls json_update_double, to_unicode
json_update_string_name_ascii calls json_update_string, to_unicode
json_update_logical calls json_add, json_info, throw_exception, json_get, to_logical
json_update_string_val_ascii calls json_update_string, to_unicode
wrap_json_update_string calls json_update_string, to_unicode
wrap_json_update_integer calls json_update_integer, to_unicode
json_update_integer calls json_add, json_info, throw_exception, json_get, to_integer
json_update_double calls json_add, json_info, throw_exception, json_get, to_double
wrap_json_update_logical calls json_update_logical, to_unicode
json_add calls wrap_json_value_add_integer, wrap_json_value_add_string, json_value_add_logical_vec, json_value_add_integer_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer_vec, wrap_json_value_add_logical, json_value_add_integer, json_value_add_double_vec, wrap_json_value_add_double_vec, wrap_json_value_add_string_vec, json_value_add_string_val_ascii, json_value_add_double, wrap_json_value_add_double, json_value_add_logical, json_value_add_string, json_value_add_string_vec, json_value_add_string_vec_name_ascii, json_value_add_string_name_ascii, json_value_add_string_vec_val_ascii, json_value_add_member
json_info calls json_count
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, wrap_json_get_string_vec_with_path, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_array, wrap_json_get_double_vec_with_path, json_get_logical, wrap_json_get_string_with_path, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_by_path
to_string calls destroy_json_data
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
wrap_json_value_add_string calls json_value_add_string, to_unicode
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string calls json_add, to_string, json_value_create, escape_string
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
to_unicode calls to_uni, to_uni_vec
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_double_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_logical_with_path calls throw_exception, json_get_logical, json_get_by_path, json_clear_exceptions
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, to_unicode
json_get_array_with_path calls throw_exception, json_get_array, json_get_by_path, json_clear_exceptions
json_get_string_with_path calls throw_exception, json_get_string, json_get_by_path, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls throw_exception, json_get_integer, json_get_by_path, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_by_path calls throw_exception, json_clear_exceptions, json_get_child, string_to_integer
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
test_2 calls json_update
test_12 calls json_update
json_file_update_string calls json_update
test_10 calls json_update
test_1 calls json_update
json_file_update_integer calls json_update
json_file_update_real calls json_update
rename calls json_update
json_file_update_logical calls json_update
jf_test_2 calls test_2
jf_test_12 calls test_12
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_10 calls test_10
jf_test_1 calls test_1
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_logical calls json_file_update_logical