json_add – JSON-Fortran
json_add Interface
Source File
Module Procedures
json_value_add_member json_value_add_integer wrap_json_value_add_integer json_value_add_integer_vec wrap_json_value_add_integer_vec json_value_add_double wrap_json_value_add_double json_value_add_double_vec wrap_json_value_add_double_vec json_value_add_logical wrap_json_value_add_logical json_value_add_logical_vec wrap_json_value_add_logical_vec json_value_add_string wrap_json_value_add_string json_value_add_string_vec wrap_json_value_add_string_vec json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public interface json_add
Add objects to a linked list of json_values.
Note
Formerly, this was called json_value_add
Calls
Called By
Module Procedures
private subroutine json_value_add_member(me, member)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
type(json_value), , pointer :: member
the child member to add
Description
Adds "member" as a child of "me".
private subroutine json_value_add_integer(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
Description
Author
Jacob Williams
Date
1/20/2014
Add an integer value child to the json_value variable
private subroutine wrap_json_value_add_integer(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in) :: val
value
Description
Alternate version of json_value_add_integer where "name" is kind=CDK.
private subroutine json_value_add_integer_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in), dimension(:) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add an integer vector to the structure.
private subroutine wrap_json_value_add_integer_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in), dimension(:) :: val
value
Description
Alternate version of json_value_add_integer_vec where "name" is kind=CDK.
private subroutine json_value_add_double(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
variable name
real(kind=RK), intent(in) :: val
real value
Description
Author
Jacob Williams
Date
1/19/2014
Add a real value child to the json_value variable
private subroutine wrap_json_value_add_double(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
variable name
real(kind=RK), intent(in) :: val
real value
Description
Alternate version of json_value_add_double where "name" is kind=CDK.
private subroutine json_value_add_double_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
real(kind=RK), intent(in), dimension(:) :: val
Description
Author
Jacob Williams
Date
1/20/2014
Add a real vector to the structure.
private subroutine wrap_json_value_add_double_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
real(kind=RK), intent(in), dimension(:) :: val
Description
Alternate version of json_value_add_double_vec where "name" is kind=CDK.
private subroutine json_value_add_logical(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add a logical value child to the json_value variable
private subroutine wrap_json_value_add_logical(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in) :: val
value
Description
Alternate version of json_value_add_logical where "name" is kind=CDK.
private subroutine json_value_add_logical_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the vector
logical(kind=LK), intent(in), dimension(:) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add a logical vector to the structure.
private subroutine wrap_json_value_add_logical_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in), dimension(:) :: val
value
Description
Alternate version of json_value_add_logical_vec where "name" is kind=CDK.
private subroutine json_value_add_string(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
character(kind=CK,len=*), intent(in) :: val
value
Description
Author
Jacob Williams
Date
1/19/2014
Add a character string child to the json_value variable.
private subroutine wrap_json_value_add_string(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
character(kind=CDK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "name" and "val" are kind=CDK.
private subroutine json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
variable name
character(kind=CK,len=*), intent(in), dimension(:) :: val
array of strings
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for each element
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for each element
Description
Author
Jacob Williams
Date
1/19/2014
Add an array of character strings to the structure.
private subroutine wrap_json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "name" and "val" are kind=CDK.
private subroutine json_value_add_string_name_ascii(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
character(kind=CK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "name" is kind=CDK.
private subroutine json_value_add_string_val_ascii(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
character(kind=CDK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "val" is kind=CDK.
private subroutine json_value_add_string_vec_name_ascii(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "name" is kind=CDK.
private subroutine json_value_add_string_vec_val_ascii(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "val" is kind=CDK.
Call graph
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_unicode calls to_uni, to_uni_vec
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data
json_update_logical calls json_add
json_update_integer calls json_add
example2 calls json_add
parse_array calls json_add, parse_value
add_variables_to_input calls json_add
json_update_double calls json_add
json_update_string calls json_add
test_2 calls json_add, add_variables_to_input, json_update
test_12 calls json_add, json_update
test_4 calls json_add
parse_object calls json_add, parse_object, parse_value
test_7 calls json_add
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_integer, json_update_double, json_update_string, wrap_json_update_logical, wrap_json_update_integer, wrap_json_update_double, wrap_json_update_string, json_update_string_name_ascii, json_update_string_val_ascii
rename calls json_update
json_file_update_logical calls json_update
json_file_update_string calls json_update
test_1 calls json_update
test_10 calls json_update
json_file_update_real calls json_update
json_file_update_integer calls json_update
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_update_integer calls json_update_integer
parse_value calls parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
test_8 calls json_parse
test_14 calls json_parse
json_file_load calls json_parse
json_file_load_from_string calls json_parse
jf_test_8 calls test_8
jf_test_14 calls test_14
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_update_double calls json_update_double
wrap_json_update_string calls json_update_string
json_update_string_name_ascii calls json_update_string
json_update_string_val_ascii calls json_update_string
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_4 calls test_4
jf_test_7 calls test_7