json_get – JSON-Fortran
json_get Interface
Source File
Module Procedures
json_get_by_path wrap_json_get_by_path json_get_integer json_get_integer_with_path wrap_json_get_integer_with_path json_get_integer_vec json_get_integer_vec_with_path wrap_json_get_integer_vec_with_path json_get_double json_get_double_with_path wrap_json_get_double_with_path json_get_double_vec json_get_double_vec_with_path wrap_json_get_double_vec_with_path json_get_logical json_get_logical_with_path wrap_json_get_logical_with_path json_get_logical_vec json_get_logical_vec_with_path wrap_json_get_logical_vec_with_path json_get_string json_get_string_with_path wrap_json_get_string_with_path json_get_string_vec json_get_string_vec_with_path wrap_json_get_string_vec_with_path json_get_array json_get_array_with_path wrap_json_get_array_with_path
All Procedures
add_variables_to_input annotate_invalid_json compact_real_string default_comp_ucs4 default_join_ucs4 destroy_json_data escape_string get_current_line_from_file_sequential get_current_line_from_file_stream initialize_json_file integer_to_string json_add json_check_for_errors json_clear_exceptions json_clone json_count json_create_array json_create_double json_create_integer json_create_logical json_create_null json_create_object json_create_string json_destroy json_failed json_file json_file_destroy json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_to_console json_file_print_to_string json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_variable_info json_get json_get_array json_get_array_with_path json_get_by_path json_get_child json_get_double json_get_double_vec json_get_double_vec_with_path json_get_double_with_path json_get_integer json_get_integer_vec json_get_integer_vec_with_path json_get_integer_with_path json_get_logical json_get_logical_vec json_get_logical_vec_with_path json_get_logical_with_path json_get_next json_get_parent json_get_previous json_get_string json_get_string_vec json_get_string_vec_with_path json_get_string_with_path json_get_tail json_info json_initialize json_parse json_parse_file json_parse_string json_print json_print_1 json_print_2 json_print_error_message json_print_to_string json_remove json_remove_if_present json_throw_exception json_traverse json_update json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_by_index json_value_get_by_name_chars json_value_print json_value_remove json_value_remove_if_present json_value_to_string operator(//) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char read_file real_to_string rename string_to_double string_to_integer test_1 test_10 test_11 test_12 test_13 test_14 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 throw_exception to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default valid_json_hex wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_variable_info wrap_json_get_array_with_path wrap_json_get_by_path wrap_json_get_double_vec_with_path wrap_json_get_double_with_path wrap_json_get_integer_vec_with_path wrap_json_get_integer_with_path wrap_json_get_logical_vec_with_path wrap_json_get_logical_with_path wrap_json_get_string_vec_with_path wrap_json_get_string_with_path wrap_json_parse_string wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_by_name_chars wrap_json_value_remove_if_present
public interface json_get
Get data from a json_value linked list.
Note
There are two versions (e.g. json_get_integer and json_get_integer_with_path). The first one gets the value from the json_value passed into the routine, while the second one gets the value from the json_value found by parsing the path. The path version is split up into unicode and non-unicode versions.
Calls
Called By
Module Procedures
private subroutine json_get_by_path(me, path, p, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
type(json_value), intent(out), pointer :: p
logical(kind=LK), intent(out), optional :: found
true if it was found
Description
Returns the json_value pointer given the path string.
private subroutine wrap_json_get_by_path(me, path, p, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
type(json_value), intent(out), pointer :: p
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_by_path where "path" is kind=CDK.
private subroutine json_get_integer(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
integer(kind=IK), intent(out) :: value
Description
Get an integer value from a json_value.
private subroutine json_get_integer_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
integer(kind=IK), intent(out) :: value
logical(kind=LK), intent(out), optional :: found
Description
Get an integer value from a json_value, given the path string.
private subroutine wrap_json_get_integer_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
integer(kind=IK), intent(out) :: value
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_integer_with_path, where "path" is kind=CDK.
private subroutine json_get_integer_vec(me, vec)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
integer(kind=IK), intent(out), dimension(:), allocatable :: vec
Description
Author
Jacob Williams
Date
5/14/2014
Get an integer vector from a json_value.
private subroutine json_get_integer_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: path
integer(kind=IK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Get an integer vector from a json_value, given the path string.
private subroutine wrap_json_get_integer_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: path
integer(kind=IK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_integer_vec_with_path, where "path" is kind=CDK
private subroutine json_get_double(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
real(kind=RK), intent(out) :: value
Description
Get a double value from a json_value.
private subroutine json_get_double_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: path
real(kind=RK), intent(out) :: value
logical(kind=LK), intent(out), optional :: found
Description
Get a double value from a json_value, given the path.
private subroutine wrap_json_get_double_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: path
real(kind=RK), intent(out) :: value
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_double_with_path, where "path" is kind=CDK
private subroutine json_get_double_vec(me, vec)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
real(kind=RK), intent(out), dimension(:), allocatable :: vec
Description
Author
Jacob Williams
Date
5/14/2014
Get a double vector from a json_value.
private subroutine json_get_double_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: path
real(kind=RK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Get a double vector from a json_value, given the path.
private subroutine wrap_json_get_double_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: path
real(kind=RK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_double_vec_with_path, where "path" is kind=CDK
private subroutine json_get_logical(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
logical(kind=LK) :: value
Description
Get a logical value from a json_value.
private subroutine json_get_logical_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
logical(kind=LK) :: value
logical(kind=LK), intent(out), optional :: found
Description
Get a logical value from a json_value, given the path.
private subroutine wrap_json_get_logical_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
logical(kind=LK) :: value
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_logical_with_path, where "path" is kind=CDK
private subroutine json_get_logical_vec(me, vec)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
logical(kind=LK), intent(out), dimension(:), allocatable :: vec
Description
Author
Jacob Williams
Date
5/14/2014
Get a logical vector from json_value.
private subroutine json_get_logical_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
logical(kind=LK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Get a logical vector from a json_value, given the path.
private subroutine wrap_json_get_logical_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
logical(kind=LK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_logical_vec_with_path, where "path" is kind=CDK
private subroutine json_get_string(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=:), intent(out), allocatable :: value
Description
Get a character string from a json_value.
private subroutine json_get_string_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
character(kind=CK,len=:), intent(out), allocatable :: value
logical(kind=LK), intent(out), optional :: found
Description
Get a character string from a json_value, given the path.
private subroutine wrap_json_get_string_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
character(kind=CK,len=:), intent(out), allocatable :: value
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_string_with_path, where "path" is kind=CDK
private subroutine json_get_string_vec(me, vec)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(out), dimension(:), allocatable :: vec
Description
Author
Jacob Williams
Date
5/14/2014
Get a string vector from a json_file.
private subroutine json_get_string_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
character(kind=CK,len=*), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Get a string vector from a json_file, given the path.
private subroutine wrap_json_get_string_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
character(kind=CK,len=*), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_string_vec_with_path, where "path" is kind=CDK
private subroutine json_get_array(me, array_callback)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
procedure(array_callback_func) :: array_callback
Description
This routine calls the user-supplied array_callback_func subroutine for each element in the array.
private subroutine json_get_array_with_path(me, path, array_callback, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
procedure(array_callback_func) :: array_callback
logical(kind=LK), intent(out), optional :: found
Description
This routine calls the user-supplied array_callback subroutine for each element in the array (specified by the path).
private subroutine wrap_json_get_array_with_path(me, path, array_callback, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: path
procedure(array_callback_func) :: array_callback
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_array_with_path, where "path" is kind=CDK
Call graph
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, wrap_json_get_string_vec_with_path, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_array, wrap_json_get_double_vec_with_path, json_get_logical, wrap_json_get_string_with_path, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_array_with_path, json_get_string_with_path, wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_by_path
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path, to_unicode
json_get_double calls throw_exception
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path, to_unicode
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
wrap_json_get_double_with_path calls json_get_double_with_path, to_unicode
json_get_double_vec calls json_get
json_get_double_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path, to_unicode
json_get_logical calls throw_exception
wrap_json_get_string_with_path calls json_get_string_with_path, to_unicode
json_get_logical_with_path calls json_get_logical, json_get_by_path, throw_exception, json_clear_exceptions
wrap_json_get_logical_with_path calls json_get_logical_with_path, to_unicode
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path, to_unicode
json_get_string calls to_unicode, throw_exception
json_get_array_with_path calls json_get_array, json_get_by_path, throw_exception, json_clear_exceptions
json_get_string_with_path calls json_get_string, json_get_by_path, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls json_get_by_path, to_unicode
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls json_get_integer, json_get_by_path, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls json_get_integer_with_path, to_unicode
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls json_get_array_with_path, to_unicode
json_get_by_path calls throw_exception, json_clear_exceptions, json_get_child, string_to_integer
to_unicode calls to_uni, to_uni_vec
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
test_2 calls json_get, json_update
json_file_get_integer_vec calls json_get
json_file_get_integer calls json_get
json_update_logical calls json_get
json_file_get_string_vec calls json_get
json_update_double calls json_get
json_file_get_double_vec calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
test_7 calls json_get
json_file_get_logical_vec calls json_get
json_file_get_double calls json_get
json_update_string calls json_get
test_12 calls json_get, json_update
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_string calls json_get
json_value_remove_if_present calls json_get
rename calls json_get, json_update
jf_test_2 calls test_2
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_integer, json_update_string, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii
json_file_update_string calls json_update
test_1 calls json_update
json_file_update_integer calls json_update
json_file_update_real calls json_update
json_file_update_logical calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_update_double calls json_update_double
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
jf_test_7 calls test_7
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_double calls json_file_get_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
jf_test_12 calls test_12
jf_test_10 calls test_10
wrap_json_file_get_string calls json_file_get_string
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present