to_unicode – JSON-Fortran
to_unicode Interface
3 statements
Source File
public interface to_unicode
Convert a 'DEFAULT' kind character input to 'ISO_10646' kind and return it
Calls
Called By
Module Procedures
to_uni to_uni_vec
Module Procedures
private pure function to_uni(str)
Author
Izaak Beekman
Convert string to unicode (CDK to CK).
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in) :: str
Return Value character(kind=CK,len=len(str))
private pure function to_uni_vec(str)
Author
Izaak Beekman
Convert array of strings to unicode (CDK to CK).
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in), dimension(:) :: str
Return Value character(kind=CK,len=len(str)), dimension(size(str))
All Procedures
annotate_invalid_json compact_real_string convert decode_rfc6901 default_comp_ucs4 default_join_ucs4 default_neq_ucs4 destroy_json_core destroy_json_data encode_rfc6901 escape_string get_current_line_from_file_sequential get_current_line_from_file_stream get_json_core_in_file initialize_json_core initialize_json_core_in_file initialize_json_file initialize_json_file_v2 integer_to_string json_add_double_by_path json_add_double_vec_by_path json_add_integer_by_path json_add_integer_vec_by_path json_add_logical_by_path json_add_logical_vec_by_path json_add_member_by_path json_add_string_by_path json_add_string_by_path_path_ascii json_add_string_by_path_value_ascii json_add_string_vec_by_path json_add_string_vec_by_path_path_ascii json_add_string_vec_by_path_value_ascii json_check_all_for_duplicate_keys json_check_children_for_duplicate_keys json_check_for_errors json_clear_exceptions json_clone json_core json_count json_create_by_path json_failed json_file json_file_add_double json_file_add_double_vec json_file_add_integer json_file_add_integer_vec json_file_add_logical json_file_add_logical_vec json_file_add_object json_file_add_string json_file_add_string_path_ascii json_file_add_string_value_ascii json_file_add_string_vec json_file_add_string_vec_path_ascii json_file_add_string_vec_vec_ascii json_file_check_for_errors json_file_clear_exceptions json_file_destroy json_file_failed json_file_get_alloc_string_vec json_file_get_double json_file_get_double_vec json_file_get_integer json_file_get_integer_vec json_file_get_logical json_file_get_logical_vec json_file_get_object json_file_get_root json_file_get_string json_file_get_string_vec json_file_load json_file_load_from_string json_file_move_pointer json_file_print_1 json_file_print_2 json_file_print_error_message json_file_print_to_console json_file_print_to_string json_file_rename json_file_rename_name_ascii json_file_rename_path_ascii json_file_traverse json_file_update_integer json_file_update_logical json_file_update_real json_file_update_string json_file_update_string_name_ascii json_file_update_string_val_ascii json_file_valid_path json_file_valid_path_op json_file_variable_info json_file_variable_matrix_info json_get_alloc_string_vec json_get_alloc_string_vec_by_path json_get_array json_get_array_by_path json_get_by_path json_get_by_path_default json_get_by_path_jsonpath_bracket json_get_by_path_rfc6901 json_get_double json_get_double_by_path json_get_double_vec json_get_double_vec_by_path json_get_integer json_get_integer_by_path json_get_integer_vec json_get_integer_vec_by_path json_get_logical json_get_logical_by_path json_get_logical_vec json_get_logical_vec_by_path json_get_next json_get_parent json_get_path json_get_previous json_get_string json_get_string_by_path json_get_string_vec json_get_string_vec_by_path json_get_tail json_info json_info_by_path json_initialize json_matrix_info json_matrix_info_by_path json_parse_file json_parse_string json_print_1 json_print_2 json_print_error_message json_rename_by_path json_rename_by_path_name_ascii json_rename_by_path_path_ascii json_string_info json_throw_exception json_traverse json_update_double json_update_integer json_update_logical json_update_string json_update_string_name_ascii json_update_string_val_ascii json_valid_path json_value_add_double json_value_add_double_vec json_value_add_integer json_value_add_integer_vec json_value_add_logical json_value_add_logical_vec json_value_add_member json_value_add_null json_value_add_string json_value_add_string_name_ascii json_value_add_string_val_ascii json_value_add_string_vec json_value_add_string_vec_name_ascii json_value_add_string_vec_val_ascii json_value_clone_func json_value_create json_value_create_array json_value_create_double json_value_create_integer json_value_create_logical json_value_create_null json_value_create_object json_value_create_string json_value_destroy json_value_get_child json_value_get_child_by_index json_value_get_child_by_name json_value_insert_after json_value_insert_after_child_by_index json_value_is_child_of json_value_print json_value_remove json_value_remove_if_present json_value_rename json_value_replace json_value_reverse json_value_swap json_value_to_string json_value_validate lowercase_string name_equal name_strings_equal operator(//) operator(/=) operator(==) parse_array parse_for_chars parse_number parse_object parse_string parse_value pop_char push_char real_to_string replace_string set_json_core_in_file string_to_dble string_to_int string_to_integer string_to_real to_array to_double to_integer to_logical to_null to_object to_string to_uni to_uni_vec to_unicode ucs4_comp_default ucs4_join_default ucs4_neq_default unescape_string valid_json_hex wrap_json_add_double_by_path wrap_json_add_double_vec_by_path wrap_json_add_integer_by_path wrap_json_add_integer_vec_by_path wrap_json_add_logical_by_path wrap_json_add_logical_vec_by_path wrap_json_add_member_by_path wrap_json_add_string_by_path wrap_json_add_string_vec_by_path wrap_json_create_by_path wrap_json_file_add_double wrap_json_file_add_double_vec wrap_json_file_add_integer wrap_json_file_add_integer_vec wrap_json_file_add_logical wrap_json_file_add_logical_vec wrap_json_file_add_object wrap_json_file_add_string wrap_json_file_add_string_vec wrap_json_file_get_alloc_string_vec wrap_json_file_get_double wrap_json_file_get_double_vec wrap_json_file_get_integer wrap_json_file_get_integer_vec wrap_json_file_get_logical wrap_json_file_get_logical_vec wrap_json_file_get_object wrap_json_file_get_string wrap_json_file_get_string_vec wrap_json_file_load_from_string wrap_json_file_rename wrap_json_file_update_integer wrap_json_file_update_logical wrap_json_file_update_real wrap_json_file_update_string wrap_json_file_valid_path wrap_json_file_valid_path_op wrap_json_file_variable_info wrap_json_file_variable_matrix_info wrap_json_get_alloc_string_vec_by_path wrap_json_get_array_by_path wrap_json_get_by_path wrap_json_get_double_by_path wrap_json_get_double_vec_by_path wrap_json_get_integer_by_path wrap_json_get_integer_vec_by_path wrap_json_get_logical_by_path wrap_json_get_logical_vec_by_path wrap_json_get_path wrap_json_get_string_by_path wrap_json_get_string_vec_by_path wrap_json_info_by_path wrap_json_matrix_info_by_path wrap_json_parse_string wrap_json_rename_by_path wrap_json_throw_exception wrap_json_update_double wrap_json_update_integer wrap_json_update_logical wrap_json_update_string wrap_json_valid_path wrap_json_value_add_double wrap_json_value_add_double_vec wrap_json_value_add_integer wrap_json_value_add_integer_vec wrap_json_value_add_logical wrap_json_value_add_logical_vec wrap_json_value_add_null wrap_json_value_add_string wrap_json_value_add_string_vec wrap_json_value_create_array wrap_json_value_create_double wrap_json_value_create_integer wrap_json_value_create_logical wrap_json_value_create_null wrap_json_value_create_object wrap_json_value_create_string wrap_json_value_get_child_by_name wrap_json_value_remove_if_present wrap_json_value_rename
Call graph
to_unicode calls to_uni, to_uni_vec
wrap_json_file_rename calls to_unicode
wrap_json_file_update_integer calls to_unicode
wrap_json_file_update_logical calls to_unicode
wrap_json_file_update_real calls to_unicode
wrap_json_file_update_string calls to_unicode
wrap_json_file_variable_info calls to_unicode
wrap_json_file_variable_matrix_info calls to_unicode
default_comp_ucs4 calls to_unicode
default_join_ucs4 calls to_unicode
default_neq_ucs4 calls to_unicode
ucs4_comp_default calls to_unicode
ucs4_join_default calls to_unicode
ucs4_neq_default calls to_unicode
wrap_json_file_valid_path_op calls to_unicode
unescape_string calls to_unicode
wrap_json_add_double_by_path calls to_unicode
wrap_json_add_double_vec_by_path calls to_unicode
wrap_json_file_add_string calls to_unicode
wrap_json_add_integer_by_path calls to_unicode
wrap_json_add_integer_vec_by_path calls to_unicode
wrap_json_add_logical_by_path calls to_unicode
wrap_json_file_valid_path calls to_unicode
wrap_json_file_get_alloc_string_vec calls to_unicode
wrap_json_add_logical_vec_by_path calls to_unicode
wrap_json_add_member_by_path calls to_unicode
wrap_json_file_add_integer_vec calls to_unicode
wrap_json_add_string_by_path calls to_unicode
wrap_json_file_get_double_vec calls to_unicode
wrap_json_add_string_vec_by_path calls to_unicode
wrap_json_create_by_path calls to_unicode
wrap_json_file_get_logical_vec calls to_unicode
wrap_json_get_alloc_string_vec_by_path calls to_unicode
wrap_json_get_array_by_path calls to_unicode
json_file_add_string_path_ascii calls to_unicode
wrap_json_file_get_logical calls to_unicode
wrap_json_get_by_path calls to_unicode
wrap_json_file_get_integer calls to_unicode
wrap_json_valid_path calls to_unicode
json_rename_by_path_name_ascii calls to_unicode
json_rename_by_path_path_ascii calls to_unicode
wrap_json_get_double_by_path calls to_unicode
wrap_json_get_double_vec_by_path calls to_unicode
wrap_json_get_integer_by_path calls to_unicode
wrap_json_file_get_double calls to_unicode
wrap_json_get_integer_vec_by_path calls to_unicode
json_file_add_string_vec_vec_ascii calls to_unicode
wrap_json_file_get_string calls to_unicode
wrap_json_get_logical_by_path calls to_unicode
json_file_add_string_vec_path_ascii calls to_unicode
json_file_update_string_name_ascii calls to_unicode
wrap_json_get_logical_vec_by_path calls to_unicode
json_file_add_string_value_ascii calls to_unicode
wrap_json_file_add_object calls to_unicode
wrap_json_get_string_by_path calls to_unicode
wrap_json_file_get_integer_vec calls to_unicode
wrap_json_get_string_vec_by_path calls to_unicode
wrap_json_info_by_path calls to_unicode
wrap_json_matrix_info_by_path calls to_unicode
wrap_json_file_add_integer calls to_unicode
wrap_json_parse_string calls to_unicode
wrap_json_file_get_string_vec calls to_unicode
json_update_string_name_ascii calls to_unicode
wrap_json_rename_by_path calls to_unicode
wrap_json_file_add_logical calls to_unicode
wrap_json_throw_exception calls to_unicode
json_update_string_val_ascii calls to_unicode
wrap_json_update_double calls to_unicode
json_add_string_by_path_path_ascii calls to_unicode
wrap_json_update_integer calls to_unicode
json_add_string_by_path_value_ascii calls to_unicode
wrap_json_update_logical calls to_unicode
wrap_json_update_string calls to_unicode
wrap_json_file_add_double calls to_unicode
json_add_string_vec_by_path_path_ascii calls to_unicode
wrap_json_value_add_double calls to_unicode
wrap_json_file_add_string_vec calls to_unicode
json_add_string_vec_by_path_value_ascii calls to_unicode
wrap_json_value_add_double_vec calls to_unicode
wrap_json_file_add_logical_vec calls to_unicode
wrap_json_value_add_integer calls to_unicode
json_file_rename_path_ascii calls to_unicode
wrap_json_value_add_integer_vec calls to_unicode
wrap_json_value_add_logical calls to_unicode
wrap_json_value_add_logical_vec calls to_unicode
json_value_add_string_name_ascii calls to_unicode
wrap_json_value_add_null calls to_unicode
wrap_json_file_add_double_vec calls to_unicode
json_value_add_string_val_ascii calls to_unicode
wrap_json_value_add_string calls to_unicode
wrap_json_value_add_string_vec calls to_unicode
wrap_json_file_get_object calls to_unicode
json_value_add_string_vec_name_ascii calls to_unicode
wrap_json_value_create_array calls to_unicode
json_file_update_string_val_ascii calls to_unicode
json_value_add_string_vec_val_ascii calls to_unicode
wrap_json_value_create_double calls to_unicode
wrap_json_value_create_integer calls to_unicode
wrap_json_file_load_from_string calls to_unicode
json_file_rename_name_ascii calls to_unicode
wrap_json_value_create_logical calls to_unicode
wrap_json_value_create_null calls to_unicode
wrap_json_value_create_object calls to_unicode
wrap_json_value_create_string calls to_unicode
wrap_json_value_get_child_by_name calls to_unicode
wrap_json_value_remove_if_present calls to_unicode
wrap_json_value_rename calls to_unicode
operator(==) calls default_comp_ucs4, ucs4_comp_default
operator(SLASHSLASH) calls default_join_ucs4, ucs4_join_default
operator(SLASH=) calls default_neq_ucs4, ucs4_neq_default
parse_string calls unescape_string