example1 – JSON-Fortran
example1 Program
Source File
Variables
json found i j k
Source Code
example1
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
json_module
Calls
Variables
Type Attributes Name Initial
type(json_file) :: json
logical :: found
integer :: i
integer :: j
integer :: k
Source Code
    program example1
        use json_module
        type(json_file) :: json
        logical :: found
        integer :: i,j,k
        ! initialize the module
        call json_initialize()
        ! read the file
        call json%load_file(filename = '../files/inputs/test1.json')
        ! print the file to the console
        call json%print_file()
        ! extract data from the file
        ! [found can be used to check if the data was really there]
        call json%get('version.major', i, found)
        if ( .not. found ) stop 1
        call json%get('version.minor', j, found)
        if ( .not. found ) stop 1
        call json%get('data(1).number', k, found)
        if ( .not. found ) stop 1
        ! clean up
        call json%destroy()
        if (json_failed()) stop 1
    end program example1
Call graph
example1 calls json_initialize, json_failed
json_initialize calls throw_exception, json_clear_exceptions
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec