example2 – JSON-Fortran
example2 Program
Source File
Variables
p inp
Source Code
example2
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
iso_fortran_env
json_module
Calls
Variables
Type Attributes Name Initial
type(json_value), pointer :: p
type(json_value), pointer :: inp
Source Code
    program example2
        use,intrinsic :: iso_fortran_env, only: wp => real64
        use json_module
        type(json_value),pointer :: p, inp
        ! initialize the module
        call json_initialize()
        ! initialize the structure:
        call json_create_object(p,'')
        ! add an "inputs" object to the structure:
        call json_create_object(inp,'inputs')
        call json_add(p, inp) !add it to the root
        ! add some data to inputs:
        call json_add(inp, 't0', 0.1_wp)
        call json_add(inp, 'tf', 1.1_wp)
        call json_add(inp, 'x0', 9999.0000d0)
        call json_add(inp, 'integer_scalar', 787)
        call json_add(inp, 'integer_array', [2,4,99])
        call json_add(inp, 'names', ['aaa','bbb','ccc'])
        call json_add(inp, 'logical_scalar', .true.)
        call json_add(inp, 'logical_vector', [.true., .false., .true.])
        nullify(inp)  !don't need this anymore
        ! write the file:
        call json_print(p,'../files/example2.json')
        !cleanup:
        call json_destroy(p)
        if (json_failed()) stop 1
    end program example2
Call graph
example2 calls json_failed, json_initialize, json_destroy, json_print, json_create_object, json_add
json_initialize calls throw_exception, json_clear_exceptions
json_destroy calls json_value_destroy
json_print calls json_print_1, json_print_2
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_value_destroy calls json_value_destroy, destroy_json_data
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls throw_exception, json_value_print, json_count, integer_to_string, write_it, real_to_string
real_to_string calls compact_real_string
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data