jf_test_10 – JSON-Fortran
jf_test_10 Program
Source File
Variables
n_errors
Source Code
jf_test_10
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
jf_test_10_mod
Tenth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_10
    !! Tenth unit test.
    use jf_test_10_mod , only: test_10
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_10(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_10
Call graph
jf_test_10 calls test_10
test_10 calls json_print_error_message, json_create_null, json_initialize, json_create_integer, json_destroy, json_get, json_create_string, json_create_double, json_create_logical, json_remove_if_present, json_update, json_create_object, json_info, json_failed
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_create_null calls wrap_json_value_create_null, json_value_create_null
json_initialize calls json_clear_exceptions, throw_exception
json_create_integer calls wrap_json_value_create_integer, json_value_create_integer
json_destroy calls json_value_destroy
json_get calls wrap_json_get_double_vec_with_path, json_get_logical, json_get_string_vec_with_path, json_get_logical_with_path, json_get_double_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_string_with_path, json_get_array, wrap_json_get_by_path, json_get_integer, wrap_json_get_string_vec_with_path, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_array_with_path, json_get_integer_vec, json_get_string_vec, json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_double_vec_with_path, wrap_json_get_array_with_path
json_create_string calls wrap_json_value_create_string, json_value_create_string
json_create_double calls wrap_json_value_create_double, json_value_create_double
json_create_logical calls json_value_create_logical, wrap_json_value_create_logical
json_remove_if_present calls wrap_json_value_remove_if_present, json_value_remove_if_present
json_update calls wrap_json_update_string, json_update_logical, json_update_string_val_ascii, json_update_integer, wrap_json_update_integer, wrap_json_update_logical, json_update_double, json_update_string, json_update_string_name_ascii, wrap_json_update_double
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_info calls json_count
wrap_json_value_create_null calls json_value_create_null, to_unicode
json_value_create_null calls to_null, json_value_create
to_unicode calls to_uni_vec, to_uni
to_null calls destroy_json_data
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
wrap_json_value_create_integer calls to_unicode, json_value_create_integer
json_value_create_integer calls json_value_create, to_integer
to_integer calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls to_unicode, throw_exception
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_string, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_array calls throw_exception, json_count
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_integer calls throw_exception
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_integer, json_get_by_path
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_integer_vec calls json_get
json_get_string_vec calls json_get
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_double_vec_with_path calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
wrap_json_value_create_string calls to_unicode, json_value_create_string
json_value_create_string calls json_value_create, to_string
to_string calls destroy_json_data
wrap_json_value_create_double calls to_unicode, json_value_create_double
json_value_create_double calls json_value_create, to_double
to_double calls destroy_json_data
json_value_create_logical calls json_value_create, to_logical
wrap_json_value_create_logical calls to_unicode, json_value_create_logical
to_logical calls destroy_json_data
wrap_json_value_remove_if_present calls to_unicode, json_value_remove_if_present
json_value_remove_if_present calls json_get, json_remove
json_remove calls json_value_remove
json_value_remove calls json_value_destroy
wrap_json_update_string calls to_unicode, json_update_string
json_update_logical calls json_get, json_info, throw_exception, to_logical, json_add
json_update_string_val_ascii calls to_unicode, json_update_string
json_update_integer calls json_get, json_info, throw_exception, to_integer, json_add
wrap_json_update_integer calls to_unicode, json_update_integer
wrap_json_update_logical calls to_unicode, json_update_logical
json_update_double calls json_get, json_info, throw_exception, to_double, json_add
json_update_string calls json_get, json_info, throw_exception, to_string, json_add
json_update_string_name_ascii calls to_unicode, json_update_string
wrap_json_update_double calls to_unicode, json_update_double
json_add calls wrap_json_value_add_integer_vec, json_value_add_integer, json_value_add_string_vec_name_ascii, wrap_json_value_add_double, json_value_add_string_vec, wrap_json_value_add_double_vec, wrap_json_value_add_logical_vec, json_value_add_double, json_value_add_integer_vec, wrap_json_value_add_string, json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_logical, wrap_json_value_add_logical, json_value_add_member, json_value_add_string_vec_val_ascii, json_value_add_double_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_integer calls json_value_create, to_integer, json_add
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec calls json_value_create, json_add, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_double calls json_value_create, to_double, json_add
json_value_add_integer_vec calls json_value_create, json_add, to_array
wrap_json_value_add_string calls to_unicode, json_value_add_string
json_value_add_string calls json_value_create, to_string, json_add, escape_string
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
json_value_add_logical_vec calls json_value_create, json_add, to_array
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_value_create, json_add, to_array
to_array calls destroy_json_data
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data