jf_test_2 – JSON-Fortran
jf_test_2 Program
Source File
Variables
n_errors
Source Code
jf_test_2
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
jf_test_2_mod
Second unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_2
    !! Second unit test.
    use jf_test_2_mod , only: test_2
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_2(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_2
Call graph
jf_test_2 calls test_2
test_2 calls json_print_error_message, add_variables_to_input, json_get_tail, json_create_array, json_info, json_destroy, json_get_previous, json_get_next, json_failed, json_initialize, json_clone, json_print, json_add, json_create_object, json_get_parent, json_update, json_get
json_print_error_message calls json_check_for_errors, json_clear_exceptions
add_variables_to_input calls json_print_error_message, json_failed, json_add, json_create_object
json_create_array calls wrap_json_value_create_array, json_value_create_array
json_info calls json_count
json_destroy calls json_value_destroy
json_initialize calls json_clear_exceptions, throw_exception
json_clone calls json_value_clone_func
json_print calls json_print_1, json_print_2
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_update calls json_update_string, json_update_string_name_ascii, wrap_json_update_double, wrap_json_update_string, json_update_logical, json_update_integer, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_integer, json_update_double
json_get calls wrap_json_get_by_path, json_get_string_vec, json_get_integer, json_get_string_vec_with_path, json_get_integer_with_path, json_get_array, wrap_json_get_integer_with_path, wrap_json_get_string_with_path, json_get_integer_vec, wrap_json_get_array_with_path, json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_logical_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_by_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_string_vec_with_path
wrap_json_value_create_array calls json_value_create_array, to_unicode
json_value_create_array calls json_value_create, to_array
to_unicode calls to_uni, to_uni_vec
to_array calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_value_clone_func calls json_value_clone_func
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls json_count, throw_exception, json_value_print, integer_to_string, write_it, real_to_string
real_to_string calls compact_real_string
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_integer calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_update_string calls json_info, json_add, json_get, throw_exception, to_string
json_update_string_name_ascii calls to_unicode, json_update_string
wrap_json_update_double calls to_unicode, json_update_double
wrap_json_update_string calls to_unicode, json_update_string
json_update_logical calls json_info, json_add, json_get, throw_exception, to_logical
json_update_integer calls json_info, json_add, json_get, throw_exception, to_integer
json_update_string_val_ascii calls to_unicode, json_update_string
wrap_json_update_logical calls to_unicode, json_update_logical
wrap_json_update_integer calls to_unicode, json_update_integer
json_update_double calls json_info, json_add, json_get, throw_exception, to_double
wrap_json_get_by_path calls to_unicode, json_get_by_path
json_get_string_vec calls json_get
json_get_integer calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_integer, json_get_by_path
json_get_array calls json_count, throw_exception
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer_vec calls json_get
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_double_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls to_unicode, throw_exception
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_by_path, json_get_string
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls json_count, throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars