jf_test_4 – JSON-Fortran
jf_test_4 Program
Source File
Variables
n_errors
Source Code
jf_test_4
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
jf_test_4_mod
Fourth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_4
    !! Fourth unit test.
    use jf_test_4_mod , only: test_4
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_4(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_4
Call graph
jf_test_4 calls test_4
test_4 calls json_print_error_message, json_print, json_destroy, json_failed, json_initialize, json_add, json_create_object, json_print_to_string
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_print calls json_print_1, json_print_2
json_destroy calls json_value_destroy
json_initialize calls json_clear_exceptions, throw_exception
json_add calls wrap_json_value_add_string, wrap_json_value_add_string_vec, wrap_json_value_add_double, wrap_json_value_add_logical, json_value_add_integer, json_value_add_string_vec_val_ascii, json_value_add_member, json_value_add_integer_vec, json_value_add_string, json_value_add_logical, json_value_add_string_vec_name_ascii, wrap_json_value_add_integer_vec, json_value_add_string_val_ascii, json_value_add_double_vec, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, json_value_add_double, json_value_add_logical_vec
json_create_object calls wrap_json_value_create_object, json_value_create_object
json_print_to_string calls json_value_to_string
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_value_print calls throw_exception, json_value_print, json_count, integer_to_string, write_it, real_to_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
real_to_string calls compact_real_string
json_value_destroy calls json_value_destroy, destroy_json_data
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_double_vec calls json_add, json_value_create, to_array
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_vec calls json_add, json_value_create, to_array
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_logical_vec calls json_add, json_value_create, to_array
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
to_logical calls destroy_json_data
to_double calls destroy_json_data
wrap_json_value_create_object calls to_unicode, json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_value_to_string calls json_value_print