jf_test_8 – JSON-Fortran
jf_test_8 Program
Source File
Variables
n_errors
Source Code
jf_test_8
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
jf_test_8_mod
Eighth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_8
    !! Eighth unit test.
    use jf_test_8_mod , only: test_8
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_8(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_8
Call graph
jf_test_8 calls test_8
test_8 calls json_print, json_destroy, json_print_error_message, json_failed, json_initialize, json_parse
json_print calls json_print_1, json_print_2
json_destroy calls json_value_destroy
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_initialize calls throw_exception, json_clear_exceptions
json_parse calls json_parse_file, wrap_json_parse_string, json_parse_string
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, integer_to_string, json_count, write_it
throw_exception calls json_throw_exception, wrap_json_throw_exception
real_to_string calls compact_real_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_value_destroy calls json_value_destroy, destroy_json_data
json_parse_file calls json_initialize, throw_exception, parse_value, json_value_create, annotate_invalid_json
wrap_json_parse_string calls to_unicode, json_parse_string
json_parse_string calls json_initialize, parse_value, json_value_create, annotate_invalid_json
parse_value calls throw_exception, to_object, to_null, pop_char, push_char, parse_object, parse_array, to_logical, parse_string, parse_number, parse_for_chars, to_string, to_array
annotate_invalid_json calls integer_to_string, get_current_line_from_file_stream, get_current_line_from_file_sequential
to_object calls destroy_json_data
to_null calls destroy_json_data
push_char calls throw_exception, integer_to_string
parse_object calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, parse_object, parse_string, json_add
parse_array calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, json_add
to_logical calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
parse_number calls throw_exception, pop_char, push_char, to_double, to_integer, string_to_double, string_to_integer
parse_for_chars calls throw_exception, pop_char
to_string calls destroy_json_data
to_array calls destroy_json_data
json_add calls wrap_json_value_add_double_vec, wrap_json_value_add_logical, json_value_add_string_vec_name_ascii, json_value_add_double, json_value_add_string_val_ascii, wrap_json_value_add_logical_vec, json_value_add_string_vec, json_value_add_logical, json_value_add_string, wrap_json_value_add_string, wrap_json_value_add_string_vec, json_value_add_double_vec, wrap_json_value_add_integer, json_value_add_string_name_ascii, json_value_add_integer_vec, wrap_json_value_add_double, wrap_json_value_add_integer_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, json_value_add_integer, json_value_add_member
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double calls json_value_create, json_add, to_double
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_value_create, to_array, json_add
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
json_value_add_integer_vec calls json_value_create, to_array, json_add
wrap_json_value_add_double calls to_unicode, json_value_add_double
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_integer calls json_value_create, json_add, to_integer
to_double calls destroy_json_data
to_integer calls destroy_json_data
string_to_double calls throw_exception
string_to_integer calls throw_exception