jf_test_14 – JSON-Fortran
jf_test_14 Program
Source File
Variables
n_errors
Source Code
jf_test_14
All Programs
example1 example2 jf_test_1 jf_test_10 jf_test_11 jf_test_12 jf_test_13 jf_test_14 jf_test_2 jf_test_3 jf_test_4 jf_test_5 jf_test_6 jf_test_7 jf_test_8 jf_test_9 test_iso_10646_support
Uses:
jf_test_14_mod
14th unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_14
    !! 14th unit test.
    use jf_test_14_mod, only: test_14
    implicit none
    integer :: n_errors
    call test_14(n_errors)
    if ( n_errors /= 0) stop 1
end program jf_test_14
Call graph
jf_test_14 calls test_14
test_14 calls json_print_error_message, json_failed, json_destroy, json_traverse, json_print, json_parse, json_initialize
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_destroy calls json_value_destroy
json_traverse calls json_traverse, json_count
json_print calls json_print_1, json_print_2
json_parse calls json_parse_file, wrap_json_parse_string, json_parse_string
json_initialize calls json_clear_exceptions, throw_exception
json_value_destroy calls json_value_destroy, destroy_json_data
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_count, json_value_print, throw_exception, write_it, integer_to_string, real_to_string
throw_exception calls json_throw_exception, wrap_json_throw_exception
real_to_string calls compact_real_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_parse_file calls json_initialize, throw_exception, annotate_invalid_json, parse_value, json_value_create
wrap_json_parse_string calls to_unicode, json_parse_string
json_parse_string calls json_initialize, annotate_invalid_json, parse_value, json_value_create
annotate_invalid_json calls integer_to_string, get_current_line_from_file_stream, get_current_line_from_file_sequential
parse_value calls throw_exception, parse_number, to_logical, to_array, parse_for_chars, to_object, parse_object, to_null, pop_char, push_char, parse_array, parse_string, to_string
parse_number calls throw_exception, pop_char, push_char, to_integer, string_to_integer, to_double, string_to_double
to_logical calls destroy_json_data
to_array calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
to_object calls destroy_json_data
parse_object calls json_destroy, throw_exception, parse_value, json_value_create, parse_object, pop_char, parse_string, json_add
to_null calls destroy_json_data
push_char calls throw_exception, integer_to_string
parse_array calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, json_add
parse_string calls throw_exception, pop_char, valid_json_hex
to_string calls destroy_json_data
to_integer calls destroy_json_data
string_to_integer calls throw_exception
to_double calls destroy_json_data
string_to_double calls throw_exception
json_add calls wrap_json_value_add_integer_vec, json_value_add_integer, json_value_add_string_vec_name_ascii, wrap_json_value_add_double, json_value_add_string_vec, wrap_json_value_add_double_vec, wrap_json_value_add_logical_vec, json_value_add_double, json_value_add_integer_vec, wrap_json_value_add_string, json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_logical, wrap_json_value_add_logical, json_value_add_member, json_value_add_string_vec_val_ascii, json_value_add_double_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
json_value_add_integer calls json_value_create, to_integer, json_add
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec calls json_value_create, to_array, json_add
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_double calls json_value_create, to_double, json_add
json_value_add_integer_vec calls json_value_create, to_array, json_add
wrap_json_value_add_string calls to_unicode, json_value_add_string
json_value_add_string calls json_value_create, to_string, json_add, escape_string
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_value_create, to_array, json_add